// This file is auto-generated by @hey-api/openapi-ts

export const BanPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        ban_type: {
            '$ref': '#/components/schemas/BanType'
        },
        expires_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Expires On'
        },
        ip: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        notes: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notes'
        },
        stats: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Stats'
        },
        server_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Server Id'
        },
        updated_by_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated By Id'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        player: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerRefPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['id', 'ban_type', 'created_on', 'updated_on'],
    title: 'BanPublic'
} as const;

export const BanTypeSchema = {
    type: 'string',
    enum: ['ban_evasion', 'bhop_hack', 'bhop_macro', 'exploiting', 'strafe_hack', 'strafe_macro', 'other'],
    title: 'BanType'
} as const;

export const BansPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/BanPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'BansPublic'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MapLeaderboardEntryPublicSchema = {
    properties: {
        map: {
            '$ref': '#/components/schemas/MapRefPublic'
        },
        tier: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tier'
        },
        review_summary: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MapReviewSummaryPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        unique_player_finishes: {
            type: 'integer',
            title: 'Unique Player Finishes'
        },
        total_finishes: {
            type: 'integer',
            title: 'Total Finishes'
        },
        total_playtime: {
            type: 'number',
            title: 'Total Playtime'
        },
        average_playtime_per_player: {
            type: 'number',
            title: 'Average Playtime Per Player'
        },
        average_finishes_per_player: {
            type: 'number',
            title: 'Average Finishes Per Player'
        },
        unique_pro_finishes: {
            type: 'integer',
            title: 'Unique Pro Finishes'
        },
        unique_nub_finishes: {
            type: 'integer',
            title: 'Unique Nub Finishes'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['map', 'unique_player_finishes', 'total_finishes', 'total_playtime', 'average_playtime_per_player', 'average_finishes_per_player', 'unique_pro_finishes', 'unique_nub_finishes'],
    title: 'MapLeaderboardEntryPublic'
} as const;

export const MapLeaderboardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MapLeaderboardEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MapLeaderboardsPublic'
} as const;

export const MapPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        filesize: {
            type: 'integer',
            title: 'Filesize'
        },
        validated: {
            type: 'boolean',
            title: 'Validated'
        },
        tiers: {
            '$ref': '#/components/schemas/MapTiers'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        approved_by_steamid64: {
            type: 'string',
            title: 'Approved By Steamid64'
        },
        workshop_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Id'
        },
        synced_at: {
            type: 'string',
            format: 'date-time',
            title: 'Synced At'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        no_steamid_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'No Steamid Names'
        },
        review_summary: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MapReviewSummaryPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        workshop_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Url',
            readOnly: true
        }
    },
    type: 'object',
    required: ['id', 'name', 'filesize', 'validated', 'tiers', 'created_on', 'updated_on', 'approved_by_steamid64', 'synced_at', 'workshop_url'],
    title: 'MapPublic'
} as const;

export const MapRefPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'MapRefPublic'
} as const;

export const MapReviewCommentInputSchema = {
    properties: {
        text: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Text'
        }
    },
    type: 'object',
    title: 'MapReviewCommentInput'
} as const;

export const MapReviewCommentPublicSchema = {
    properties: {
        text: {
            type: 'string',
            title: 'Text'
        },
        language: {
            type: 'string',
            title: 'Language'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['text', 'language', 'created_at', 'updated_at'],
    title: 'MapReviewCommentPublic'
} as const;

export const MapReviewContentInputSchema = {
    properties: {
        overall: {
            type: 'integer',
            maximum: 5,
            minimum: 1,
            title: 'Overall'
        },
        gameplay: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gameplay'
        },
        visuals: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 5,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visuals'
        },
        comment: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MapReviewCommentInput'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['overall'],
    title: 'MapReviewContentInput'
} as const;

export const MapReviewContentPublicSchema = {
    properties: {
        overall: {
            type: 'integer',
            title: 'Overall'
        },
        gameplay: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gameplay'
        },
        visuals: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visuals'
        },
        comment: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/MapReviewCommentPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['overall'],
    title: 'MapReviewContentPublic'
} as const;

export const MapReviewPublicSchema = {
    properties: {
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        server_group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Server Group Id'
        },
        content: {
            '$ref': '#/components/schemas/MapReviewContentPublic'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        map: {
            '$ref': '#/components/schemas/MapRefPublic'
        }
    },
    type: 'object',
    required: ['steamid64', 'map_id', 'content', 'created_at', 'updated_at', 'player', 'map'],
    title: 'MapReviewPublic'
} as const;

export const MapReviewSummaryPublicSchema = {
    properties: {
        overall_avg: {
            type: 'number',
            title: 'Overall Avg'
        },
        gameplay_avg: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gameplay Avg'
        },
        visuals_avg: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visuals Avg'
        },
        reviews_count: {
            type: 'integer',
            title: 'Reviews Count'
        },
        gameplay_count: {
            type: 'integer',
            title: 'Gameplay Count'
        },
        visuals_count: {
            type: 'integer',
            title: 'Visuals Count'
        },
        comments_count: {
            type: 'integer',
            title: 'Comments Count'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['overall_avg', 'reviews_count', 'gameplay_count', 'visuals_count', 'comments_count', 'updated_at'],
    title: 'MapReviewSummaryPublic'
} as const;

export const MapReviewUpsertSchema = {
    properties: {
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        steamid64: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steamid64'
        },
        content: {
            '$ref': '#/components/schemas/MapReviewContentInput'
        }
    },
    type: 'object',
    required: ['map_id', 'content'],
    title: 'MapReviewUpsert'
} as const;

export const MapReviewsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/MapReviewPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'MapReviewsPublic'
} as const;

export const MapSyncResultSchema = {
    properties: {
        processed: {
            type: 'integer',
            title: 'Processed'
        },
        created: {
            type: 'integer',
            title: 'Created'
        },
        updated: {
            type: 'integer',
            title: 'Updated'
        },
        errors: {
            type: 'integer',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['processed', 'created', 'updated', 'errors'],
    title: 'MapSyncResult'
} as const;

export const MapTiersSchema = {
    properties: {
        OVR: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ovr'
        },
        KZT: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Kzt'
        },
        SKZ: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Skz'
        },
        VNL: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vnl'
        }
    },
    type: 'object',
    required: ['OVR', 'KZT', 'SKZ', 'VNL'],
    title: 'MapTiers'
} as const;

export const MapWrPublicSchema = {
    properties: {
        record_uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Record Uuid'
        },
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        scope: {
            '$ref': '#/components/schemas/ModeScope'
        },
        type: {
            '$ref': '#/components/schemas/RecordType'
        },
        mode_id: {
            type: 'integer',
            title: 'Mode Id'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        time: {
            type: 'number',
            title: 'Time'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['record_uuid', 'map_id', 'scope', 'type', 'mode_id', 'player', 'time', 'updated_at'],
    title: 'MapWrPublic'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModeAdminUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1023
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        latest_version: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version'
        },
        latest_version_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version Description'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        repo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo'
        },
        contact_steamid64: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Steamid64'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ModeAdminUpdate'
} as const;

export const ModePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        id_plugin: {
            type: 'integer',
            title: 'Id Plugin'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        latest_version: {
            type: 'integer',
            title: 'Latest Version'
        },
        latest_version_description: {
            type: 'string',
            title: 'Latest Version Description'
        },
        website: {
            type: 'string',
            title: 'Website'
        },
        repo: {
            type: 'string',
            title: 'Repo'
        },
        contact_steamid64: {
            type: 'string',
            title: 'Contact Steamid64'
        },
        supported_tickrates: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supported Tickrates'
        },
        created_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created On'
        },
        updated_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated On'
        },
        updated_by_id: {
            type: 'string',
            title: 'Updated By Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'name_short', 'id_plugin', 'description', 'latest_version', 'latest_version_description', 'website', 'repo', 'contact_steamid64', 'updated_by_id'],
    title: 'ModePublic'
} as const;

export const ModeScopeSchema = {
    type: 'string',
    enum: ['OVR', 'KZT', 'SKZ', 'VNL'],
    title: 'ModeScope'
} as const;

export const PlayerDailyActivityDayPublicSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        count: {
            type: 'integer',
            minimum: 0,
            title: 'Count'
        }
    },
    type: 'object',
    required: ['date', 'count'],
    title: 'PlayerDailyActivityDayPublic'
} as const;

export const PlayerDailyActivityPublicSchema = {
    properties: {
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        days: {
            items: {
                '$ref': '#/components/schemas/PlayerDailyActivityDayPublic'
            },
            type: 'array',
            title: 'Days'
        }
    },
    type: 'object',
    required: ['updated_at'],
    title: 'PlayerDailyActivityPublic'
} as const;

export const PlayerFollowSummaryPublicSchema = {
    properties: {
        follower_count: {
            type: 'integer',
            title: 'Follower Count',
            default: 0
        },
        following_count: {
            type: 'integer',
            title: 'Following Count',
            default: 0
        },
        viewer_is_following: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Viewer Is Following'
        },
        viewer_is_self: {
            type: 'boolean',
            title: 'Viewer Is Self',
            default: false
        }
    },
    type: 'object',
    title: 'PlayerFollowSummaryPublic'
} as const;

export const PlayerLeaderboardEntryPublicSchema = {
    properties: {
        rank: {
            type: 'integer',
            title: 'Rank'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        rating_easy: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating Easy'
        },
        rating_hard: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating Hard'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        wrs_nub: {
            type: 'integer',
            title: 'Wrs Nub'
        },
        wrs_pro: {
            type: 'integer',
            title: 'Wrs Pro'
        },
        records_900_plus: {
            type: 'integer',
            title: 'Records 900 Plus'
        },
        records_800_plus: {
            type: 'integer',
            title: 'Records 800 Plus'
        },
        unique_map_finishes: {
            type: 'integer',
            title: 'Unique Map Finishes'
        }
    },
    type: 'object',
    required: ['rank', 'player', 'rating', 'rating_easy', 'rating_hard', 'points', 'wrs_nub', 'wrs_pro', 'records_900_plus', 'records_800_plus', 'unique_map_finishes'],
    title: 'PlayerLeaderboardEntryPublic'
} as const;

export const PlayerLeaderboardRankPublicSchema = {
    properties: {
        scope: {
            '$ref': '#/components/schemas/ModeScope'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        rank_regional: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank Regional'
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        rating: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating'
        },
        rating_easy: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating Easy'
        },
        rating_hard: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rating Hard'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        wrs_nub: {
            type: 'integer',
            title: 'Wrs Nub'
        },
        wrs_pro: {
            type: 'integer',
            title: 'Wrs Pro'
        },
        records_900_plus: {
            type: 'integer',
            title: 'Records 900 Plus'
        },
        records_800_plus: {
            type: 'integer',
            title: 'Records 800 Plus'
        },
        unique_map_finishes: {
            type: 'integer',
            title: 'Unique Map Finishes'
        }
    },
    type: 'object',
    required: ['scope', 'player', 'rating', 'rating_easy', 'rating_hard', 'points', 'wrs_nub', 'wrs_pro', 'records_900_plus', 'records_800_plus', 'unique_map_finishes'],
    title: 'PlayerLeaderboardRankPublic'
} as const;

export const PlayerLeaderboardsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerLeaderboardEntryPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayerLeaderboardsPublic'
} as const;

export const PlayerPinnedRecordPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        player_steamid64: {
            type: 'string',
            title: 'Player Steamid64'
        },
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        scope: {
            '$ref': '#/components/schemas/ModeScope'
        },
        type: {
            '$ref': '#/components/schemas/RecordType'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        record: {
            '$ref': '#/components/schemas/RecordPublic'
        }
    },
    type: 'object',
    required: ['id', 'player_steamid64', 'map_id', 'scope', 'type', 'created_at', 'updated_at', 'record'],
    title: 'PlayerPinnedRecordPublic'
} as const;

export const PlayerPinnedRecordUpsertSchema = {
    properties: {
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        scope: {
            '$ref': '#/components/schemas/ModeScope'
        },
        type: {
            '$ref': '#/components/schemas/RecordType'
        }
    },
    type: 'object',
    required: ['map_id', 'scope', 'type'],
    title: 'PlayerPinnedRecordUpsert'
} as const;

export const PlayerPinnedRecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPinnedRecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayerPinnedRecordsPublic'
} as const;

export const PlayerPlaytimePublicSchema = {
    properties: {
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        total_seconds: {
            type: 'number',
            minimum: 0,
            title: 'Total Seconds',
            default: 0
        }
    },
    type: 'object',
    required: ['updated_at'],
    title: 'PlayerPlaytimePublic'
} as const;

export const PlayerProfileViewsPublicSchema = {
    properties: {
        profile_views: {
            type: 'integer',
            title: 'Profile Views',
            default: 0
        }
    },
    type: 'object',
    title: 'PlayerProfileViewsPublic'
} as const;

export const PlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        custom_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Id'
        },
        avatar_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Hash'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_played_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Played At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        is_website_user: {
            type: 'boolean',
            title: 'Is Website User',
            default: false
        },
        profile_views: {
            type: 'integer',
            title: 'Profile Views',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'steamid64'],
    title: 'PlayerPublic'
} as const;

export const PlayerRefPublicSchema = {
    properties: {
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        display_name: {
            type: 'string',
            title: 'Display Name'
        }
    },
    type: 'object',
    required: ['steamid64', 'display_name'],
    title: 'PlayerRefPublic'
} as const;

export const PlayerStatTypeSchema = {
    type: 'string',
    enum: ['daily_activity', 'playtime'],
    title: 'PlayerStatType'
} as const;

export const PlayerStatsPublicSchema = {
    properties: {
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        daily_activity: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerDailyActivityPublic'
                },
                {
                    type: 'null'
                }
            ]
        },
        playtime: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerPlaytimePublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['steamid64'],
    title: 'PlayerStatsPublic'
} as const;

export const PlayerUpdateSchema = {
    properties: {
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        }
    },
    type: 'object',
    title: 'PlayerUpdate'
} as const;

export const PlayersBatchPublicSchema = {
    properties: {
        data: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/PlayerPublic'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersBatchPublic'
} as const;

export const PlayersBatchReadSchema = {
    properties: {
        steamid64s: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Steamid64S'
        }
    },
    type: 'object',
    required: ['steamid64s'],
    title: 'PlayersBatchRead'
} as const;

export const PlayersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersPublic'
} as const;

export const RecentRecordMapPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'integer',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['id', 'name', 'tier'],
    title: 'RecentRecordMapPublic'
} as const;

export const RecentRecordModePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RecentRecordModePublic'
} as const;

export const RecentRecordPublicSchema = {
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Uuid'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        map: {
            '$ref': '#/components/schemas/RecentRecordMapPublic'
        },
        server: {
            '$ref': '#/components/schemas/RecentRecordServerPublic'
        },
        mode: {
            '$ref': '#/components/schemas/RecentRecordModePublic'
        },
        stage: {
            type: 'integer',
            title: 'Stage'
        },
        teleports: {
            type: 'integer',
            title: 'Teleports'
        },
        time: {
            type: 'number',
            title: 'Time'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        }
    },
    type: 'object',
    required: ['uuid', 'player', 'map', 'server', 'mode', 'stage', 'teleports', 'time', 'points', 'created_on', 'updated_on'],
    title: 'RecentRecordPublic'
} as const;

export const RecentRecordServerPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RecentRecordServerPublic'
} as const;

export const RecentRecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecentRecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecentRecordsPublic'
} as const;

export const RecordPatchSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['is_valid'],
    title: 'RecordPatch'
} as const;

export const RecordPublicSchema = {
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Uuid'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        player: {
            '$ref': '#/components/schemas/PlayerRefPublic'
        },
        steam_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steam Id'
        },
        server_id: {
            type: 'integer',
            title: 'Server Id'
        },
        server_name: {
            type: 'string',
            title: 'Server Name'
        },
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        map_name: {
            type: 'string',
            title: 'Map Name'
        },
        map_tier: {
            type: 'integer',
            title: 'Map Tier'
        },
        mode_id: {
            type: 'integer',
            title: 'Mode Id'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        stage: {
            type: 'integer',
            title: 'Stage'
        },
        tickrate: {
            type: 'integer',
            title: 'Tickrate',
            default: 128
        },
        time: {
            type: 'number',
            title: 'Time'
        },
        teleports: {
            type: 'integer',
            title: 'Teleports'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        updated_by: {
            type: 'string',
            title: 'Updated By'
        },
        replay_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Replay Id'
        },
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        }
    },
    type: 'object',
    required: ['uuid', 'player', 'server_id', 'server_name', 'map_id', 'map_name', 'map_tier', 'mode_id', 'mode', 'stage', 'time', 'teleports', 'points', 'created_on', 'updated_on', 'updated_by', 'is_valid'],
    title: 'RecordPublic'
} as const;

export const RecordRankPublicSchema = {
    properties: {
        record_uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Record Uuid'
        },
        rank: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rank'
        },
        total_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Total Count'
        }
    },
    type: 'object',
    required: ['record_uuid'],
    title: 'RecordRankPublic'
} as const;

export const RecordRanksPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecordRankPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecordRanksPublic'
} as const;

export const RecordTypeSchema = {
    type: 'string',
    enum: ['NUB', 'PRO'],
    title: 'RecordType'
} as const;

export const RecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecordsPublic'
} as const;

export const RegionCodeSchema = {
    type: 'string',
    enum: ['AF', 'AS', 'CIS', 'CN', 'EU', 'ME', 'NA', 'OC', 'SA'],
    title: 'RegionCode'
} as const;

export const RegionPublicSchema = {
    properties: {
        code: {
            '$ref': '#/components/schemas/RegionCode'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        country_codes: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Country Codes'
        }
    },
    type: 'object',
    required: ['code', 'name', 'country_codes'],
    title: 'RegionPublic'
} as const;

export const RegionsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RegionPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RegionsPublic'
} as const;

export const ServerCreateSchema = {
    properties: {
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        status: {
            '$ref': '#/components/schemas/ServerStatus',
            default: 'enabled'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        }
    },
    type: 'object',
    required: ['ip', 'port'],
    title: 'ServerCreate'
} as const;

export const ServerDiscoveryRunPublicSchema = {
    properties: {
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Completed At'
        },
        regions_scanned: {
            type: 'integer',
            title: 'Regions Scanned'
        },
        candidate_count: {
            type: 'integer',
            title: 'Candidate Count'
        },
        upserted_count: {
            type: 'integer',
            title: 'Upserted Count'
        }
    },
    type: 'object',
    required: ['started_at', 'completed_at', 'regions_scanned', 'candidate_count', 'upserted_count'],
    title: 'ServerDiscoveryRunPublic'
} as const;

export const ServerGroupApiKeyPublicSchema = {
    properties: {
        group: {
            '$ref': '#/components/schemas/ServerGroupPublic'
        },
        api_key: {
            type: 'string',
            title: 'Api Key'
        }
    },
    type: 'object',
    required: ['group', 'api_key'],
    title: 'ServerGroupApiKeyPublic'
} as const;

export const ServerGroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ServerGroupCreate'
} as const;

export const ServerGroupPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_steamid64: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Owner Steamid64'
        },
        status: {
            '$ref': '#/components/schemas/ServerGroupStatus'
        },
        server_count: {
            type: 'integer',
            title: 'Server Count',
            default: 0
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'status', 'created_at', 'updated_at'],
    title: 'ServerGroupPublic'
} as const;

export const ServerGroupStatusSchema = {
    type: 'string',
    enum: ['pending', 'validated', 'invalidated'],
    title: 'ServerGroupStatus'
} as const;

export const ServerGroupSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ServerGroupSummary'
} as const;

export const ServerGroupUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerGroupStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'ServerGroupUpdate'
} as const;

export const ServerGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServerGroupsPublic'
} as const;

export const ServerHistoryBucketPublicSchema = {
    properties: {
        bucket_start: {
            type: 'string',
            format: 'date-time',
            title: 'Bucket Start'
        },
        heartbeat_count: {
            type: 'integer',
            title: 'Heartbeat Count'
        },
        hostname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hostname'
        },
        map: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            title: 'Player Count'
        },
        max_players: {
            type: 'integer',
            title: 'Max Players'
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        },
        is_online: {
            type: 'boolean',
            title: 'Is Online'
        }
    },
    type: 'object',
    required: ['bucket_start', 'heartbeat_count', 'player_count', 'max_players', 'is_online'],
    title: 'ServerHistoryBucketPublic'
} as const;

export const ServerHistoryPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerHistoryBucketPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServerHistoryPublic'
} as const;

export const ServerLiveStatusPublicSchema = {
    properties: {
        hostname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hostname'
        },
        map: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            minimum: 0,
            title: 'Player Count',
            default: 0
        },
        max_players: {
            type: 'integer',
            minimum: 0,
            title: 'Max Players',
            default: 0
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        },
        is_online: {
            type: 'boolean',
            title: 'Is Online',
            default: false
        },
        state: {
            '$ref': '#/components/schemas/ServerLiveStatusStatePublic'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['updated_at'],
    title: 'ServerLiveStatusPublic'
} as const;

export const ServerLiveStatusStatePublicSchema = {
    properties: {
        last_plugin_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Plugin Seen At'
        },
        last_a2s_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last A2S Seen At'
        },
        last_successful_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Successful Seen At'
        },
        last_valid_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Valid Seen At'
        },
        invalid_count: {
            type: 'integer',
            minimum: 0,
            title: 'Invalid Count',
            default: 0
        },
        timeout_count: {
            type: 'integer',
            minimum: 0,
            title: 'Timeout Count',
            default: 0
        }
    },
    type: 'object',
    title: 'ServerLiveStatusStatePublic'
} as const;

export const ServerPublicSchema = {
    properties: {
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        status: {
            '$ref': '#/components/schemas/ServerStatus',
            default: 'enabled'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        region: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Region'
        },
        source: {
            additionalProperties: true,
            type: 'object',
            title: 'Source'
        },
        last_discovered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Discovered At'
        },
        map_tier: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map Tier'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        group: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerGroupSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        live_status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerLiveStatusPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['ip', 'port', 'id', 'source', 'created_at', 'updated_at'],
    title: 'ServerPublic'
} as const;

export const ServerSourceSchema = {
    type: 'string',
    enum: ['manual', 'steam_master'],
    title: 'ServerSource'
} as const;

export const ServerStatusSchema = {
    type: 'string',
    enum: ['enabled', 'invalid', 'disabled'],
    title: 'ServerStatus'
} as const;

export const ServerStatusPutSchema = {
    properties: {
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        },
        hostname: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Hostname'
        },
        map: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            minimum: 0,
            title: 'Player Count'
        },
        max_players: {
            type: 'integer',
            minimum: 0,
            title: 'Max Players'
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        }
    },
    type: 'object',
    required: ['ip', 'port', 'observed_at', 'hostname', 'map', 'player_count', 'max_players'],
    title: 'ServerStatusPut'
} as const;

export const ServerUpdateSchema = {
    properties: {
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        ip: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerStatus'
                },
                {
                    type: 'null'
                }
            ]
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        }
    },
    type: 'object',
    title: 'ServerUpdate'
} as const;

export const ServersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServersPublic'
} as const;

export const UserPublicSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_visited_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Visited At'
        },
        player: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerRefPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['steamid64'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;