// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ItemCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title'],
    title: 'ItemCreate'
} as const;

export const ItemPublicSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        owner_id: {
            type: 'string',
            title: 'Owner Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['title', 'id', 'owner_id'],
    title: 'ItemPublic'
} as const;

export const ItemUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    title: 'ItemUpdate'
} as const;

export const ItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ItemsPublic'
} as const;

export const MapPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        filesize: {
            type: 'integer',
            title: 'Filesize'
        },
        validated: {
            type: 'boolean',
            title: 'Validated'
        },
        difficulty: {
            type: 'integer',
            title: 'Difficulty'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        approved_by_steamid64: {
            type: 'string',
            title: 'Approved By Steamid64'
        },
        workshop_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Id'
        },
        synced_at: {
            type: 'string',
            format: 'date-time',
            title: 'Synced At'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        no_steamid_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'No Steamid Names'
        },
        workshop_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Url',
            readOnly: true
        }
    },
    type: 'object',
    required: ['id', 'name', 'filesize', 'validated', 'difficulty', 'created_on', 'updated_on', 'approved_by_steamid64', 'synced_at', 'workshop_url'],
    title: 'MapPublic'
} as const;

export const MapSyncResultSchema = {
    properties: {
        processed: {
            type: 'integer',
            title: 'Processed'
        },
        created: {
            type: 'integer',
            title: 'Created'
        },
        updated: {
            type: 'integer',
            title: 'Updated'
        },
        errors: {
            type: 'integer',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['processed', 'created', 'updated', 'errors'],
    title: 'MapSyncResult'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModeAdminUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1023
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        latest_version: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version'
        },
        latest_version_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version Description'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        repo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo'
        },
        contact_steamid64: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Steamid64'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ModeAdminUpdate'
} as const;

export const ModePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        id_plugin: {
            type: 'integer',
            title: 'Id Plugin'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        latest_version: {
            type: 'integer',
            title: 'Latest Version'
        },
        latest_version_description: {
            type: 'string',
            title: 'Latest Version Description'
        },
        website: {
            type: 'string',
            title: 'Website'
        },
        repo: {
            type: 'string',
            title: 'Repo'
        },
        contact_steamid64: {
            type: 'string',
            title: 'Contact Steamid64'
        },
        supported_tickrates: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supported Tickrates'
        },
        created_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created On'
        },
        updated_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated On'
        },
        updated_by_id: {
            type: 'string',
            title: 'Updated By Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'name_short', 'id_plugin', 'description', 'latest_version', 'latest_version_description', 'website', 'repo', 'contact_steamid64', 'updated_by_id'],
    title: 'ModePublic'
} as const;

export const PlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        custom_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Id'
        },
        avatar_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Hash'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_played_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Played At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        }
    },
    type: 'object',
    required: ['name', 'steamid64'],
    title: 'PlayerPublic'
} as const;

export const PlayerUpdateSchema = {
    properties: {
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        }
    },
    type: 'object',
    title: 'PlayerUpdate'
} as const;

export const PlayersBatchPublicSchema = {
    properties: {
        data: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/PlayerPublic'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersBatchPublic'
} as const;

export const PlayersBatchReadSchema = {
    properties: {
        steamid64s: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Steamid64S'
        }
    },
    type: 'object',
    required: ['steamid64s'],
    title: 'PlayersBatchRead'
} as const;

export const PlayersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersPublic'
} as const;

export const PrivateAuthSessionCreateSchema = {
    properties: {
        steamid64: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Steamid64',
            default: '76561199022242128'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: true
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            default: 'Docs Admin'
        }
    },
    type: 'object',
    title: 'PrivateAuthSessionCreate',
    example: {
        is_active: true,
        is_superuser: true,
        name: 'Docs Admin',
        steamid64: '76561199022242128'
    }
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_visited_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Visited At'
        },
        player: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['steamid64'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;