// This file is auto-generated by @hey-api/openapi-ts

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MapPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        filesize: {
            type: 'integer',
            title: 'Filesize'
        },
        validated: {
            type: 'boolean',
            title: 'Validated'
        },
        tiers: {
            '$ref': '#/components/schemas/MapTiers'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        approved_by_steamid64: {
            type: 'string',
            title: 'Approved By Steamid64'
        },
        workshop_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Id'
        },
        synced_at: {
            type: 'string',
            format: 'date-time',
            title: 'Synced At'
        },
        authors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Authors'
        },
        no_steamid_names: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'No Steamid Names'
        },
        workshop_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Workshop Url',
            readOnly: true
        }
    },
    type: 'object',
    required: ['id', 'name', 'filesize', 'validated', 'tiers', 'created_on', 'updated_on', 'approved_by_steamid64', 'synced_at', 'workshop_url'],
    title: 'MapPublic'
} as const;

export const MapSyncResultSchema = {
    properties: {
        processed: {
            type: 'integer',
            title: 'Processed'
        },
        created: {
            type: 'integer',
            title: 'Created'
        },
        updated: {
            type: 'integer',
            title: 'Updated'
        },
        errors: {
            type: 'integer',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['processed', 'created', 'updated', 'errors'],
    title: 'MapSyncResult'
} as const;

export const MapTiersSchema = {
    properties: {
        OVR: {
            type: 'integer',
            title: 'Ovr'
        },
        KZT: {
            type: 'integer',
            title: 'Kzt'
        },
        SKZ: {
            type: 'integer',
            title: 'Skz'
        },
        VNL: {
            type: 'integer',
            title: 'Vnl'
        }
    },
    type: 'object',
    required: ['OVR', 'KZT', 'SKZ', 'VNL'],
    title: 'MapTiers'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const ModeAdminUpdateSchema = {
    properties: {
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 1023
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        latest_version: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 0
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version'
        },
        latest_version_description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Latest Version Description'
        },
        website: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website'
        },
        repo: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Repo'
        },
        contact_steamid64: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 32
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contact Steamid64'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'ModeAdminUpdate'
} as const;

export const ModePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        name_short: {
            type: 'string',
            title: 'Name Short'
        },
        id_plugin: {
            type: 'integer',
            title: 'Id Plugin'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        latest_version: {
            type: 'integer',
            title: 'Latest Version'
        },
        latest_version_description: {
            type: 'string',
            title: 'Latest Version Description'
        },
        website: {
            type: 'string',
            title: 'Website'
        },
        repo: {
            type: 'string',
            title: 'Repo'
        },
        contact_steamid64: {
            type: 'string',
            title: 'Contact Steamid64'
        },
        supported_tickrates: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Supported Tickrates'
        },
        created_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created On'
        },
        updated_on: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated On'
        },
        updated_by_id: {
            type: 'string',
            title: 'Updated By Id'
        }
    },
    type: 'object',
    required: ['id', 'name', 'name_short', 'id_plugin', 'description', 'latest_version', 'latest_version_description', 'website', 'repo', 'contact_steamid64', 'updated_by_id'],
    title: 'ModePublic'
} as const;

export const PlayerFollowSummaryPublicSchema = {
    properties: {
        follower_count: {
            type: 'integer',
            title: 'Follower Count',
            default: 0
        },
        following_count: {
            type: 'integer',
            title: 'Following Count',
            default: 0
        },
        viewer_is_following: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Viewer Is Following'
        },
        viewer_is_self: {
            type: 'boolean',
            title: 'Viewer Is Self',
            default: false
        }
    },
    type: 'object',
    title: 'PlayerFollowSummaryPublic'
} as const;

export const PlayerProfileViewsPublicSchema = {
    properties: {
        profile_views: {
            type: 'integer',
            title: 'Profile Views',
            default: 0
        }
    },
    type: 'object',
    title: 'PlayerProfileViewsPublic'
} as const;

export const PlayerPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        custom_id: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Custom Id'
        },
        avatar_hash: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Hash'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_played_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Played At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        profile_views: {
            type: 'integer',
            title: 'Profile Views',
            default: 0
        }
    },
    type: 'object',
    required: ['name', 'steamid64'],
    title: 'PlayerPublic'
} as const;

export const PlayerUpdateSchema = {
    properties: {
        alias: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 25
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        }
    },
    type: 'object',
    title: 'PlayerUpdate'
} as const;

export const PlayersBatchPublicSchema = {
    properties: {
        data: {
            items: {
                anyOf: [
                    {
                        '$ref': '#/components/schemas/PlayerPublic'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersBatchPublic'
} as const;

export const PlayersBatchReadSchema = {
    properties: {
        steamid64s: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Steamid64S'
        }
    },
    type: 'object',
    required: ['steamid64s'],
    title: 'PlayersBatchRead'
} as const;

export const PlayersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/PlayerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'PlayersPublic'
} as const;

export const PrivateAuthSessionCreateSchema = {
    properties: {
        steamid64: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'integer'
                }
            ],
            title: 'Steamid64',
            default: '76561199022242128'
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: true
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name',
            default: 'Docs Admin'
        }
    },
    type: 'object',
    title: 'PrivateAuthSessionCreate',
    example: {
        is_active: true,
        is_superuser: true,
        name: 'Docs Admin',
        steamid64: '76561199022242128'
    }
} as const;

export const RecentRecordMapPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        tier: {
            type: 'integer',
            title: 'Tier'
        }
    },
    type: 'object',
    required: ['id', 'name', 'tier'],
    title: 'RecentRecordMapPublic'
} as const;

export const RecentRecordModePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RecentRecordModePublic'
} as const;

export const RecentRecordPlayerPublicSchema = {
    properties: {
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        alias: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Alias'
        },
        avatar_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Avatar Hash'
        },
        country: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        }
    },
    type: 'object',
    required: ['steamid64', 'name'],
    title: 'RecentRecordPlayerPublic'
} as const;

export const RecentRecordPublicSchema = {
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Uuid'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        player: {
            '$ref': '#/components/schemas/RecentRecordPlayerPublic'
        },
        map: {
            '$ref': '#/components/schemas/RecentRecordMapPublic'
        },
        server: {
            '$ref': '#/components/schemas/RecentRecordServerPublic'
        },
        mode: {
            '$ref': '#/components/schemas/RecentRecordModePublic'
        },
        stage: {
            type: 'integer',
            title: 'Stage'
        },
        teleports: {
            type: 'integer',
            title: 'Teleports'
        },
        time: {
            type: 'number',
            title: 'Time'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        }
    },
    type: 'object',
    required: ['uuid', 'player', 'map', 'server', 'mode', 'stage', 'teleports', 'time', 'points', 'created_on', 'updated_on'],
    title: 'RecentRecordPublic'
} as const;

export const RecentRecordServerPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'RecentRecordServerPublic'
} as const;

export const RecentRecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecentRecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecentRecordsPublic'
} as const;

export const RecordPatchSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        }
    },
    additionalProperties: false,
    type: 'object',
    required: ['is_valid'],
    title: 'RecordPatch'
} as const;

export const RecordPublicSchema = {
    properties: {
        uuid: {
            type: 'string',
            format: 'uuid',
            title: 'Uuid'
        },
        id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Id'
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        player_name: {
            type: 'string',
            title: 'Player Name'
        },
        player_avatar_hash: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Player Avatar Hash'
        },
        steam_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Steam Id'
        },
        server_id: {
            type: 'integer',
            title: 'Server Id'
        },
        server_name: {
            type: 'string',
            title: 'Server Name'
        },
        map_id: {
            type: 'integer',
            title: 'Map Id'
        },
        map_name: {
            type: 'string',
            title: 'Map Name'
        },
        map_tier: {
            type: 'integer',
            title: 'Map Tier'
        },
        mode_id: {
            type: 'integer',
            title: 'Mode Id'
        },
        mode: {
            type: 'string',
            title: 'Mode'
        },
        stage: {
            type: 'integer',
            title: 'Stage'
        },
        tickrate: {
            type: 'integer',
            title: 'Tickrate',
            default: 128
        },
        time: {
            type: 'number',
            title: 'Time'
        },
        teleports: {
            type: 'integer',
            title: 'Teleports'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        created_on: {
            type: 'string',
            format: 'date-time',
            title: 'Created On'
        },
        updated_on: {
            type: 'string',
            format: 'date-time',
            title: 'Updated On'
        },
        updated_by: {
            type: 'string',
            title: 'Updated By'
        },
        replay_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Replay Id'
        },
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        }
    },
    type: 'object',
    required: ['uuid', 'steamid64', 'player_name', 'server_id', 'server_name', 'map_id', 'map_name', 'map_tier', 'mode_id', 'mode', 'stage', 'time', 'teleports', 'points', 'created_on', 'updated_on', 'updated_by', 'is_valid'],
    title: 'RecordPublic'
} as const;

export const RecordScopeSchema = {
    type: 'string',
    enum: ['OVR', 'KZT', 'SKZ', 'VNL'],
    title: 'RecordScope'
} as const;

export const RecordsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/RecordPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'RecordsPublic'
} as const;

export const ServerCreateSchema = {
    properties: {
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        }
    },
    type: 'object',
    required: ['ip', 'port'],
    title: 'ServerCreate'
} as const;

export const ServerDiscoveryRunPublicSchema = {
    properties: {
        started_at: {
            type: 'string',
            format: 'date-time',
            title: 'Started At'
        },
        completed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Completed At'
        },
        regions_scanned: {
            type: 'integer',
            title: 'Regions Scanned'
        },
        candidate_count: {
            type: 'integer',
            title: 'Candidate Count'
        },
        upserted_count: {
            type: 'integer',
            title: 'Upserted Count'
        }
    },
    type: 'object',
    required: ['started_at', 'completed_at', 'regions_scanned', 'candidate_count', 'upserted_count'],
    title: 'ServerDiscoveryRunPublic'
} as const;

export const ServerGroupApiKeyPublicSchema = {
    properties: {
        group: {
            '$ref': '#/components/schemas/ServerGroupPublic'
        },
        api_key: {
            type: 'string',
            title: 'Api Key'
        }
    },
    type: 'object',
    required: ['group', 'api_key'],
    title: 'ServerGroupApiKeyPublic'
} as const;

export const ServerGroupCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'ServerGroupCreate'
} as const;

export const ServerGroupPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        api_key_prefix: {
            type: 'string',
            title: 'Api Key Prefix'
        },
        api_key_created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Api Key Created At'
        },
        server_count: {
            type: 'integer',
            title: 'Server Count',
            default: 0
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: ['name', 'id', 'api_key_prefix', 'api_key_created_at', 'created_at', 'updated_at'],
    title: 'ServerGroupPublic'
} as const;

export const ServerGroupSummarySchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['id', 'name'],
    title: 'ServerGroupSummary'
} as const;

export const ServerGroupUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        }
    },
    type: 'object',
    title: 'ServerGroupUpdate'
} as const;

export const ServerGroupsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerGroupPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServerGroupsPublic'
} as const;

export const ServerHistoryBucketPublicSchema = {
    properties: {
        bucket_start: {
            type: 'string',
            format: 'date-time',
            title: 'Bucket Start'
        },
        heartbeat_count: {
            type: 'integer',
            title: 'Heartbeat Count'
        },
        hostname: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hostname'
        },
        map: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            title: 'Player Count'
        },
        max_players: {
            type: 'integer',
            title: 'Max Players'
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        },
        is_online: {
            type: 'boolean',
            title: 'Is Online'
        }
    },
    type: 'object',
    required: ['bucket_start', 'heartbeat_count', 'player_count', 'max_players', 'is_online'],
    title: 'ServerHistoryBucketPublic'
} as const;

export const ServerHistoryPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerHistoryBucketPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServerHistoryPublic'
} as const;

export const ServerLiveStatusPublicSchema = {
    properties: {
        current_hostname: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Hostname'
        },
        map: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            minimum: 0,
            title: 'Player Count',
            default: 0
        },
        max_players: {
            type: 'integer',
            minimum: 0,
            title: 'Max Players',
            default: 0
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        },
        is_online: {
            type: 'boolean',
            title: 'Is Online',
            default: false
        },
        last_plugin_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Plugin Seen At'
        },
        last_a2s_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last A2S Seen At'
        },
        last_successful_seen_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Successful Seen At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    title: 'ServerLiveStatusPublic'
} as const;

export const ServerPublicSchema = {
    properties: {
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        enabled: {
            type: 'boolean',
            title: 'Enabled',
            default: true
        },
        configured_hostname: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Configured Hostname'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        source: {
            '$ref': '#/components/schemas/ServerSource'
        },
        last_discovered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Discovered At'
        },
        map_tier: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Map Tier'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        group: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerGroupSummary'
                },
                {
                    type: 'null'
                }
            ]
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/ServerLiveStatusPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['ip', 'port', 'id', 'source', 'created_at', 'updated_at'],
    title: 'ServerPublic'
} as const;

export const ServerSourceSchema = {
    type: 'string',
    enum: ['manual', 'steam_master'],
    title: 'ServerSource'
} as const;

export const ServerStatusPutSchema = {
    properties: {
        ip: {
            type: 'string',
            maxLength: 64,
            minLength: 1,
            title: 'Ip'
        },
        port: {
            type: 'integer',
            maximum: 65535,
            minimum: 1,
            title: 'Port'
        },
        observed_at: {
            type: 'string',
            format: 'date-time',
            title: 'Observed At'
        },
        hostname: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Hostname'
        },
        map: {
            type: 'string',
            maxLength: 255,
            minLength: 1,
            title: 'Map'
        },
        player_count: {
            type: 'integer',
            minimum: 0,
            title: 'Player Count'
        },
        max_players: {
            type: 'integer',
            minimum: 0,
            title: 'Max Players'
        },
        players: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Players'
        }
    },
    type: 'object',
    required: ['ip', 'port', 'observed_at', 'hostname', 'map', 'player_count', 'max_players'],
    title: 'ServerStatusPut'
} as const;

export const ServerUpdateSchema = {
    properties: {
        group_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Group Id'
        },
        ip: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 64,
                    minLength: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ip'
        },
        port: {
            anyOf: [
                {
                    type: 'integer',
                    maximum: 65535,
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Port'
        },
        enabled: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Enabled'
        },
        configured_hostname: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Configured Hostname'
        },
        country: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country'
        },
        city: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'City'
        }
    },
    type: 'object',
    title: 'ServerUpdate'
} as const;

export const ServersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ServerPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ServersPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        steamid64: {
            type: 'string',
            title: 'Steamid64'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        last_visited_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Visited At'
        },
        player: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/PlayerPublic'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: ['steamid64'],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;