// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MapPublic = {
    id: number;
    name: string;
    filesize: number;
    validated: boolean;
    tiers: MapTiers;
    created_on: string;
    updated_on: string;
    approved_by_steamid64: string;
    workshop_id?: (number | null);
    synced_at: string;
    authors?: Array<(string)>;
    no_steamid_names?: Array<(string)>;
    readonly workshop_url: (string | null);
};

export type MapSyncResult = {
    processed: number;
    created: number;
    updated: number;
    errors: number;
};

export type MapTiers = {
    OVR: number;
    KZT: number;
    SKZ: number;
    VNL: number;
};

export type Message = {
    message: string;
};

export type ModeAdminUpdate = {
    description?: (string | null);
    latest_version?: (number | null);
    latest_version_description?: (string | null);
    website?: (string | null);
    repo?: (string | null);
    contact_steamid64?: (string | null);
};

export type ModePublic = {
    id: number;
    name: string;
    name_short: string;
    id_plugin: number;
    description: string;
    latest_version: number;
    latest_version_description: string;
    website: string;
    repo: string;
    contact_steamid64: string;
    supported_tickrates?: (Array<(number)> | null);
    created_on?: (string | null);
    updated_on?: (string | null);
    updated_by_id: string;
};

export type PlayerPublic = {
    name: string;
    alias?: (string | null);
    custom_id?: (string | null);
    avatar_hash?: (string | null);
    country?: (string | null);
    created_at?: (string | null);
    last_played_at?: (string | null);
    updated_at?: (string | null);
    steamid64: string;
};

export type PlayersBatchPublic = {
    data: Array<(PlayerPublic | null)>;
    count: number;
};

export type PlayersBatchRead = {
    steamid64s: Array<(string)>;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerUpdate = {
    alias?: (string | null);
    country?: (string | null);
};

export type PrivateAuthSessionCreate = {
    steamid64?: (string | number);
    is_superuser?: boolean;
    is_active?: boolean;
    name?: (string | null);
};

export type RecentRecordMapPublic = {
    id: number;
    name: string;
    tier: number;
};

export type RecentRecordModePublic = {
    id: number;
    name: string;
};

export type RecentRecordPlayerPublic = {
    steamid64: string;
    name: string;
    alias?: (string | null);
    avatar_hash?: (string | null);
    country?: (string | null);
};

export type RecentRecordPublic = {
    uuid: string;
    id?: (number | null);
    player: RecentRecordPlayerPublic;
    map: RecentRecordMapPublic;
    server: RecentRecordServerPublic;
    mode: RecentRecordModePublic;
    stage: number;
    teleports: number;
    time: number;
    points: number;
    created_on: string;
    updated_on: string;
};

export type RecentRecordServerPublic = {
    id: number;
    name: string;
};

export type RecentRecordsPublic = {
    data: Array<RecentRecordPublic>;
    count: number;
};

export type RecordPatch = {
    is_valid: boolean;
};

export type RecordPublic = {
    uuid: string;
    id?: (number | null);
    steamid64: string;
    player_name: string;
    player_avatar_hash?: (string | null);
    steam_id?: (string | null);
    server_id: number;
    server_name: string;
    map_id: number;
    map_name: string;
    map_tier: number;
    mode_id: number;
    mode: string;
    stage: number;
    tickrate?: number;
    time: number;
    teleports: number;
    points: number;
    created_on: string;
    updated_on: string;
    updated_by: string;
    replay_id?: (number | null);
    is_valid: boolean;
};

export type RecordScope = 'OVR' | 'KZT' | 'SKZ' | 'VNL';

export type RecordsPublic = {
    data: Array<RecordPublic>;
    count: number;
};

export type ServerCreate = {
    group_id?: (string | null);
    ip: string;
    port: number;
    enabled?: boolean;
    country?: (string | null);
    city?: (string | null);
};

export type ServerDiscoveryRunPublic = {
    started_at: string;
    completed_at: string;
    regions_scanned: number;
    candidate_count: number;
    upserted_count: number;
};

export type ServerGroupApiKeyPublic = {
    group: ServerGroupPublic;
    api_key: string;
};

export type ServerGroupCreate = {
    name: string;
};

export type ServerGroupPublic = {
    name: string;
    id: string;
    api_key_prefix: string;
    api_key_created_at: string;
    server_count?: number;
    created_at: string;
    updated_at: string;
};

export type ServerGroupsPublic = {
    data: Array<ServerGroupPublic>;
    count: number;
};

export type ServerGroupSummary = {
    id: string;
    name: string;
};

export type ServerGroupUpdate = {
    name?: (string | null);
};

export type ServerHistoryBucketPublic = {
    bucket_start: string;
    heartbeat_count: number;
    hostname?: (string | null);
    map?: (string | null);
    player_count: number;
    max_players: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
    is_online: boolean;
};

export type ServerHistoryPublic = {
    data: Array<ServerHistoryBucketPublic>;
    count: number;
};

export type ServerLiveStatusPublic = {
    current_hostname?: (string | null);
    map?: (string | null);
    player_count?: number;
    max_players?: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
    is_online?: boolean;
    last_plugin_seen_at?: (string | null);
    last_a2s_seen_at?: (string | null);
    last_successful_seen_at?: (string | null);
    updated_at?: string;
};

export type ServerPublic = {
    ip: string;
    port: number;
    enabled?: boolean;
    configured_hostname?: (string | null);
    country?: (string | null);
    city?: (string | null);
    id: string;
    group_id?: (string | null);
    source: ServerSource;
    last_discovered_at?: (string | null);
    map_tier?: (number | null);
    created_at: string;
    updated_at: string;
    group?: (ServerGroupSummary | null);
    status?: (ServerLiveStatusPublic | null);
};

export type ServerSource = 'manual' | 'steam_master';

export type ServersPublic = {
    data: Array<ServerPublic>;
    count: number;
};

export type ServerStatusPut = {
    ip: string;
    port: number;
    observed_at: string;
    hostname: string;
    map: string;
    player_count: number;
    max_players: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
};

export type ServerUpdate = {
    group_id?: (string | null);
    ip?: (string | null);
    port?: (number | null);
    enabled?: (boolean | null);
    configured_hostname?: (string | null);
    country?: (string | null);
    city?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    is_active?: boolean;
    is_superuser?: boolean;
    steamid64: string;
    created_at?: (string | null);
    last_visited_at?: (string | null);
    player?: (PlayerPublic | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminModesUpdateModeData = {
    id: number;
    requestBody: ModeAdminUpdate;
};

export type AdminModesUpdateModeResponse = (ModePublic);

export type LoginLoginSteamResponse = (unknown);

export type LoginSteamCallbackResponse = (unknown);

export type LoginTestTokenResponse = (UserPublic);

export type MapsReadMapsData = {
    createdSince?: (string | null);
    id?: (Array<(number)> | null);
    isValidated?: (boolean | null);
    largerThanFilesize?: (number | null);
    limit?: number;
    name?: (string | null);
    offset?: number;
    smallerThanFilesize?: (number | null);
    updatedSince?: (string | null);
};

export type MapsReadMapsResponse = (Array<MapPublic>);

export type MapsReadMapByNameData = {
    mapName: string;
};

export type MapsReadMapByNameResponse = (MapPublic);

export type MapsReadMapByIdData = {
    id: number;
};

export type MapsReadMapByIdResponse = (MapPublic);

export type MapsTriggerMapSyncResponse = (MapSyncResult);

export type ModesReadModesResponse = (Array<ModePublic>);

export type ModesReadModeByNameData = {
    modeName: string;
};

export type ModesReadModeByNameResponse = (ModePublic);

export type ModesReadModeByIdData = {
    id: number;
};

export type ModesReadModeByIdResponse = (ModePublic);

export type PlayersReadPlayersData = {
    limit?: number;
    offset?: number;
    sortBy?: 'created_at' | 'last_played_at';
    sortOrder?: 'asc' | 'desc';
};

export type PlayersReadPlayersResponse = (PlayersPublic);

export type PlayersReadPlayersBatchData = {
    requestBody: PlayersBatchRead;
};

export type PlayersReadPlayersBatchResponse = (PlayersBatchPublic);

export type PlayersReadPlayerData = {
    identifier: string;
};

export type PlayersReadPlayerResponse = (PlayerPublic);

export type PlayersUpsertPlayerFromSteamData = {
    steamid64: string;
};

export type PlayersUpsertPlayerFromSteamResponse = (PlayerPublic);

export type PlayersUpdatePlayerData = {
    requestBody: PlayerUpdate;
    steamid64: string;
};

export type PlayersUpdatePlayerResponse = (PlayerPublic);

export type PrivateCreateAuthSessionData = {
    requestBody: PrivateAuthSessionCreate;
};

export type PrivateCreateAuthSessionResponse = (Token);

export type RecordsReadRecordsData = {
    createdSince?: (string | null);
    id?: (Array<(number)> | null);
    isValid?: (boolean | null);
    limit?: number;
    mapId?: (number | null);
    modeId?: (number | null);
    offset?: number;
    replayId?: (number | null);
    scope?: RecordScope;
    serverId?: (number | null);
    stage?: (number | null);
    steamid64?: (number | null);
    teleports?: (number | null);
    updatedSince?: (string | null);
};

export type RecordsReadRecordsResponse = (RecordsPublic);

export type RecordsReadRecentRecordsData = {
    isProOnly?: (boolean | null);
    limit?: number;
    offset?: number;
    pointsMoreOrEqualThan?: (number | null);
    scope?: RecordScope;
};

export type RecordsReadRecentRecordsResponse = (RecentRecordsPublic);

export type RecordsReadPbRecordsData = {
    isProOnly?: boolean;
    limit?: number;
    mapId?: (number | null);
    offset?: number;
    scope?: RecordScope;
    stage?: number;
    steamid64?: (string | null);
};

export type RecordsReadPbRecordsResponse = (Array<RecordPublic>);

export type RecordsReadRecordData = {
    recordUuid: string;
    scope?: RecordScope;
};

export type RecordsReadRecordResponse = (RecordPublic);

export type RecordsPatchRecordData = {
    recordUuid: string;
    requestBody: RecordPatch;
};

export type RecordsPatchRecordResponse = (RecordPublic);

export type ServerGroupsReadServerGroupsResponse = (ServerGroupsPublic);

export type ServerGroupsCreateServerGroupData = {
    requestBody: ServerGroupCreate;
};

export type ServerGroupsCreateServerGroupResponse = (ServerGroupApiKeyPublic);

export type ServerGroupsUpdateServerGroupData = {
    groupId: string;
    requestBody: ServerGroupUpdate;
};

export type ServerGroupsUpdateServerGroupResponse = (ServerGroupPublic);

export type ServerGroupsDeleteServerGroupData = {
    groupId: string;
};

export type ServerGroupsDeleteServerGroupResponse = (Message);

export type ServerGroupsRotateServerGroupApiKeyData = {
    groupId: string;
};

export type ServerGroupsRotateServerGroupApiKeyResponse = (ServerGroupApiKeyPublic);

export type ServersPutServerStatusData = {
    requestBody: ServerStatusPut;
    xServerGroupKey?: (string | null);
};

export type ServersPutServerStatusResponse = (ServerPublic);

export type ServersReadServersData = {
    city?: (string | null);
    country?: (string | null);
    groupId?: (string | null);
    limit?: number;
    offset?: number;
    online?: (boolean | null);
    source?: (ServerSource | null);
};

export type ServersReadServersResponse = (ServersPublic);

export type ServersCreateServerData = {
    requestBody: ServerCreate;
};

export type ServersCreateServerResponse = (ServerPublic);

export type ServersTriggerServerDiscoveryResponse = (ServerDiscoveryRunPublic);

export type ServersReadServerHistoryData = {
    bucketSeconds?: number;
    fromAt?: (string | null);
    serverId: string;
    toAt?: (string | null);
};

export type ServersReadServerHistoryResponse = (ServerHistoryPublic);

export type ServersReadServerData = {
    serverId: string;
};

export type ServersReadServerResponse = (ServerPublic);

export type ServersUpdateServerData = {
    requestBody: ServerUpdate;
    serverId: string;
};

export type ServersUpdateServerResponse = (ServerPublic);

export type ServersDeleteServerData = {
    serverId: string;
};

export type ServersDeleteServerResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);