// This file is auto-generated by @hey-api/openapi-ts

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type PlayerPublic = {
    name: string;
    alias?: (string | null);
    custom_id?: (string | null);
    avatar_hash?: (string | null);
    country?: (string | null);
    created_at?: (string | null);
    last_played_at?: (string | null);
    updated_at?: (string | null);
    steamid64: string;
};

export type PlayersBatchPublic = {
    data: Array<(PlayerPublic | null)>;
    count: number;
};

export type PlayersBatchRead = {
    steamid64s: Array<(string)>;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerUpdate = {
    alias?: (string | null);
    country?: (string | null);
};

export type PrivateAuthSessionCreate = {
    steamid64: number;
    is_superuser?: boolean;
    is_active?: boolean;
    name?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    is_active?: boolean;
    is_superuser?: boolean;
    steamid64: string;
    created_at?: (string | null);
    last_visited_at?: (string | null);
    player?: (PlayerPublic | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginSteamResponse = (unknown);

export type LoginSteamCallbackResponse = (unknown);

export type LoginTestTokenResponse = (UserPublic);

export type PlayersReadPlayersData = {
    limit?: number;
    offset?: number;
    sortBy?: 'created_at' | 'last_played_at';
    sortOrder?: 'asc' | 'desc';
};

export type PlayersReadPlayersResponse = (PlayersPublic);

export type PlayersReadPlayersBatchData = {
    requestBody: PlayersBatchRead;
};

export type PlayersReadPlayersBatchResponse = (PlayersBatchPublic);

export type PlayersUpsertPlayerFromSteamData = {
    steamid64: string;
};

export type PlayersUpsertPlayerFromSteamResponse = (PlayerPublic);

export type PlayersUpdatePlayerData = {
    requestBody: PlayerUpdate;
    steamid64: string;
};

export type PlayersUpdatePlayerResponse = (PlayerPublic);

export type PrivateCreateAuthSessionData = {
    requestBody: PrivateAuthSessionCreate;
};

export type PrivateCreateAuthSessionResponse = (Token);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);