// This file is auto-generated by @hey-api/openapi-ts

export type BanPublic = {
    id: number;
    ban_type: BanType;
    expires_on?: (string | null);
    ip?: (string | null);
    notes?: (string | null);
    stats?: (string | null);
    server_id?: (number | null);
    updated_by_id?: (string | null);
    created_on: string;
    updated_on: string;
    player?: (PlayerRefPublic | null);
};

export type BansPublic = {
    data: Array<BanPublic>;
    count: number;
};

export type BanType = 'ban_evasion' | 'bhop_hack' | 'bhop_macro' | 'exploiting' | 'strafe_hack' | 'strafe_macro' | 'other';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MapPublic = {
    id: number;
    name: string;
    filesize: number;
    validated: boolean;
    tiers: MapTiers;
    created_on: string;
    updated_on: string;
    approved_by_steamid64: string;
    workshop_id?: (number | null);
    synced_at: string;
    authors?: Array<(string)>;
    no_steamid_names?: Array<(string)>;
    review_summary?: (MapReviewSummaryPublic | null);
    readonly workshop_url: (string | null);
};

export type MapRefPublic = {
    id: number;
    name: string;
};

export type MapReviewCommentInput = {
    text?: (string | null);
};

export type MapReviewCommentPublic = {
    text: string;
    language: string;
    created_at: string;
    updated_at: string;
};

export type MapReviewContentInput = {
    overall: number;
    gameplay?: (number | null);
    visuals?: (number | null);
    comment?: (MapReviewCommentInput | null);
};

export type MapReviewContentPublic = {
    overall: number;
    gameplay?: (number | null);
    visuals?: (number | null);
    comment?: (MapReviewCommentPublic | null);
};

export type MapReviewPublic = {
    steamid64: string;
    map_id: number;
    server_group_id?: (string | null);
    content: MapReviewContentPublic;
    created_at: string;
    updated_at: string;
    player: PlayerRefPublic;
    map: MapRefPublic;
};

export type MapReviewsPublic = {
    data: Array<MapReviewPublic>;
    count: number;
};

export type MapReviewSummaryPublic = {
    overall_avg: number;
    gameplay_avg?: (number | null);
    visuals_avg?: (number | null);
    reviews_count: number;
    gameplay_count: number;
    visuals_count: number;
    comments_count: number;
    updated_at: string;
};

export type MapReviewUpsert = {
    map_id: number;
    steamid64?: (number | null);
    content: MapReviewContentInput;
};

export type MapSyncResult = {
    processed: number;
    created: number;
    updated: number;
    errors: number;
};

export type MapTiers = {
    OVR: (number | null);
    KZT: (number | null);
    SKZ: (number | null);
    VNL: (number | null);
};

export type MapWrPublic = {
    record_uuid: string;
    map_id: number;
    scope: RecordScope;
    type: RecordType;
    mode_id: number;
    player: PlayerRefPublic;
    time: number;
    updated_at: string;
};

export type Message = {
    message: string;
};

export type ModeAdminUpdate = {
    description?: (string | null);
    latest_version?: (number | null);
    latest_version_description?: (string | null);
    website?: (string | null);
    repo?: (string | null);
    contact_steamid64?: (string | null);
};

export type ModePublic = {
    id: number;
    name: string;
    name_short: string;
    id_plugin: number;
    description: string;
    latest_version: number;
    latest_version_description: string;
    website: string;
    repo: string;
    contact_steamid64: string;
    supported_tickrates?: (Array<(number)> | null);
    created_on?: (string | null);
    updated_on?: (string | null);
    updated_by_id: string;
};

export type PlayerDailyActivityContentPublic = {
    days?: Array<PlayerDailyActivityDayPublic>;
};

export type PlayerDailyActivityDayPublic = {
    date: string;
    count: number;
};

export type PlayerDailyActivityStatPublic = {
    steamid64: string;
    type: PlayerStatType;
    updated_at: string;
    content: PlayerDailyActivityContentPublic;
};

export type PlayerFollowSummaryPublic = {
    follower_count?: number;
    following_count?: number;
    viewer_is_following?: (boolean | null);
    viewer_is_self?: boolean;
};

export type PlayerLeaderboardEntryPublic = {
    rank: number;
    player: PlayerRefPublic;
    rating: (number | null);
    rating_easy: (number | null);
    rating_hard: (number | null);
    points: number;
    wrs_nub: number;
    wrs_pro: number;
    records_900_plus: number;
    records_800_plus: number;
    unique_map_finishes: number;
};

export type PlayerLeaderboardRankPublic = {
    scope: RecordScope;
    rank?: (number | null);
    rank_regional?: (number | null);
    region?: (string | null);
    player: PlayerRefPublic;
    rating: (number | null);
    rating_easy: (number | null);
    rating_hard: (number | null);
    points: number;
    wrs_nub: number;
    wrs_pro: number;
    records_900_plus: number;
    records_800_plus: number;
    unique_map_finishes: number;
};

export type PlayerLeaderboardsPublic = {
    data: Array<PlayerLeaderboardEntryPublic>;
    count: number;
};

export type PlayerPinnedRecordPublic = {
    id: string;
    player_steamid64: string;
    map_id: number;
    scope: RecordScope;
    type: RecordType;
    created_at: string;
    updated_at: string;
    record: RecordPublic;
};

export type PlayerPinnedRecordsPublic = {
    data: Array<PlayerPinnedRecordPublic>;
    count: number;
};

export type PlayerPinnedRecordUpsert = {
    map_id: number;
    scope: RecordScope;
    type: RecordType;
};

export type PlayerProfileViewsPublic = {
    profile_views?: number;
};

export type PlayerPublic = {
    name: string;
    alias?: (string | null);
    custom_id?: (string | null);
    avatar_hash?: (string | null);
    country?: (string | null);
    created_at?: (string | null);
    last_played_at?: (string | null);
    updated_at?: (string | null);
    steamid64: string;
    is_website_user?: boolean;
    profile_views?: number;
};

export type PlayerRefPublic = {
    steamid64: string;
    display_name: string;
};

export type PlayersBatchPublic = {
    data: Array<(PlayerPublic | null)>;
    count: number;
};

export type PlayersBatchRead = {
    steamid64s: Array<(string)>;
};

export type PlayersPublic = {
    data: Array<PlayerPublic>;
    count: number;
};

export type PlayerStatType = 'daily_activity';

export type PlayerUpdate = {
    alias?: (string | null);
    country?: (string | null);
};

export type RecentRecordMapPublic = {
    id: number;
    name: string;
    tier: number;
};

export type RecentRecordModePublic = {
    id: number;
    name: string;
};

export type RecentRecordPublic = {
    uuid: string;
    id?: (number | null);
    player: PlayerRefPublic;
    map: RecentRecordMapPublic;
    server: RecentRecordServerPublic;
    mode: RecentRecordModePublic;
    stage: number;
    teleports: number;
    time: number;
    points: number;
    created_on: string;
    updated_on: string;
};

export type RecentRecordServerPublic = {
    id: number;
    name: string;
};

export type RecentRecordsPublic = {
    data: Array<RecentRecordPublic>;
    count: number;
};

export type RecordPatch = {
    is_valid: boolean;
};

export type RecordPublic = {
    uuid: string;
    id?: (number | null);
    player: PlayerRefPublic;
    steam_id?: (string | null);
    server_id: number;
    server_name: string;
    map_id: number;
    map_name: string;
    map_tier: number;
    mode_id: number;
    mode: string;
    stage: number;
    tickrate?: number;
    time: number;
    teleports: number;
    points: number;
    created_on: string;
    updated_on: string;
    updated_by: string;
    replay_id?: (number | null);
    is_valid: boolean;
};

export type RecordRankPublic = {
    record_uuid: string;
    rank?: (number | null);
    total_count?: (number | null);
};

export type RecordRanksPublic = {
    data: Array<RecordRankPublic>;
    count: number;
};

export type RecordScope = 'OVR' | 'KZT' | 'SKZ' | 'VNL';

export type RecordsPublic = {
    data: Array<RecordPublic>;
    count: number;
};

export type RecordType = 'NUB' | 'PRO';

export type RegionCode = 'AF' | 'AS' | 'CIS' | 'CN' | 'EU' | 'ME' | 'NA' | 'OC' | 'SA';

export type RegionPublic = {
    code: RegionCode;
    name: string;
    country_codes: Array<(string)>;
};

export type RegionsPublic = {
    data: Array<RegionPublic>;
    count: number;
};

export type ServerCreate = {
    group_id?: (string | null);
    ip: string;
    port: number;
    status?: ServerStatus;
    country?: (string | null);
    city?: (string | null);
};

export type ServerDiscoveryRunPublic = {
    started_at: string;
    completed_at: string;
    regions_scanned: number;
    candidate_count: number;
    upserted_count: number;
};

export type ServerGroupApiKeyPublic = {
    group: ServerGroupPublic;
    api_key: string;
};

export type ServerGroupCreate = {
    name: string;
};

export type ServerGroupPublic = {
    name: string;
    id: string;
    owner_steamid64?: (string | null);
    status: ServerGroupStatus;
    server_count?: number;
    created_at: string;
    updated_at: string;
};

export type ServerGroupsPublic = {
    data: Array<ServerGroupPublic>;
    count: number;
};

export type ServerGroupStatus = 'pending' | 'validated' | 'invalidated';

export type ServerGroupSummary = {
    id: string;
    name: string;
};

export type ServerGroupUpdate = {
    name?: (string | null);
    status?: (ServerGroupStatus | null);
};

export type ServerHistoryBucketPublic = {
    bucket_start: string;
    heartbeat_count: number;
    hostname?: (string | null);
    map?: (string | null);
    player_count: number;
    max_players: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
    is_online: boolean;
};

export type ServerHistoryPublic = {
    data: Array<ServerHistoryBucketPublic>;
    count: number;
};

export type ServerLiveStatusPublic = {
    hostname?: (string | null);
    map?: (string | null);
    player_count?: number;
    max_players?: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
    is_online?: boolean;
    state?: ServerLiveStatusStatePublic;
    updated_at: string;
};

export type ServerLiveStatusStatePublic = {
    last_plugin_seen_at?: (string | null);
    last_a2s_seen_at?: (string | null);
    last_successful_seen_at?: (string | null);
    last_valid_seen_at?: (string | null);
    invalid_count?: number;
    timeout_count?: number;
};

export type ServerPublic = {
    ip: string;
    port: number;
    status?: ServerStatus;
    country?: (string | null);
    city?: (string | null);
    id: string;
    group_id?: (string | null);
    region?: (string | null);
    source: {
        [key: string]: unknown;
    };
    last_discovered_at?: (string | null);
    map_tier?: (number | null);
    created_at: string;
    updated_at: string;
    group?: (ServerGroupSummary | null);
    live_status?: (ServerLiveStatusPublic | null);
};

export type ServerSource = 'manual' | 'steam_master';

export type ServersPublic = {
    data: Array<ServerPublic>;
    count: number;
};

export type ServerStatus = 'enabled' | 'invalid' | 'disabled';

export type ServerStatusPut = {
    ip: string;
    port: number;
    observed_at: string;
    hostname: string;
    map: string;
    player_count: number;
    max_players: number;
    players?: Array<{
        [key: string]: unknown;
    }>;
};

export type ServerUpdate = {
    group_id?: (string | null);
    ip?: (string | null);
    port?: (number | null);
    status?: (ServerStatus | null);
    country?: (string | null);
    city?: (string | null);
};

export type UserPublic = {
    is_active?: boolean;
    is_superuser?: boolean;
    steamid64: string;
    created_at?: (string | null);
    last_visited_at?: (string | null);
    player?: (PlayerRefPublic | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AdminModesUpdateModeData = {
    id: number;
    requestBody: ModeAdminUpdate;
};

export type AdminModesUpdateModeResponse = (ModePublic);

export type BansReadBansData = {
    banTypes?: (string | null);
    banTypesList?: (Array<(string)> | null);
    createdSince?: (string | null);
    ip?: (string | null);
    isExpired?: (boolean | null);
    limit?: number;
    notesContains?: (string | null);
    offset?: number;
    serverId?: (number | null);
    statsContains?: (string | null);
    steamid64?: (number | null);
    updatedSince?: (string | null);
};

export type BansReadBansResponse = (BansPublic);

export type BansReadBanData = {
    id: number;
};

export type BansReadBanResponse = (BanPublic);

export type HandleHttpGetResponse = (unknown);

export type HandleHttpPostResponse = (unknown);

export type LeaderboardsReadPlayerLeaderboardData = {
    country?: (string | null);
    includeCount?: boolean;
    limit?: number;
    offset?: number;
    region?: (string | null);
    scope?: RecordScope;
    sortBy?: 'rating' | 'rating_easy' | 'rating_hard' | 'points' | 'wrs_nub' | 'wrs_pro' | 'records_900_plus' | 'records_800_plus' | 'unique_map_finishes';
    sortOrder?: "desc";
};

export type LeaderboardsReadPlayerLeaderboardResponse = (PlayerLeaderboardsPublic);

export type LeaderboardsReadPlayerLeaderboardRankData = {
    country?: (string | null);
    identifier: string;
    region?: (string | null);
    scope?: RecordScope;
};

export type LeaderboardsReadPlayerLeaderboardRankResponse = (PlayerLeaderboardRankPublic);

export type LeaderboardsUpsertPlayerLeaderboardsData = {
    identifier: string;
};

export type LeaderboardsUpsertPlayerLeaderboardsResponse = (Message);

export type LoginLoginSteamResponse = (unknown);

export type LoginSteamCallbackResponse = (unknown);

export type LoginTestTokenResponse = (UserPublic);

export type MapsReadMapsData = {
    createdSince?: (string | null);
    id?: (Array<(number)> | null);
    isValidated?: (boolean | null);
    largerThanFilesize?: (number | null);
    limit?: number;
    name?: (string | null);
    offset?: number;
    smallerThanFilesize?: (number | null);
    updatedSince?: (string | null);
};

export type MapsReadMapsResponse = (Array<MapPublic>);

export type MapsReadMapByNameData = {
    mapName: string;
};

export type MapsReadMapByNameResponse = (MapPublic);

export type MapsReadMapWrsData = {
    mapId?: (number | null);
    mapName?: (string | null);
    scope?: RecordScope;
    type?: (RecordType | null);
};

export type MapsReadMapWrsResponse = (Array<MapWrPublic>);

export type MapsReadMapByIdData = {
    id: number;
};

export type MapsReadMapByIdResponse = (MapPublic);

export type MapsReadMapReviewsData = {
    language?: (string | null);
    limit?: number;
    mapId?: (number | null);
    mapName?: (string | null);
    offset?: number;
    source?: 'latest' | 'website';
    steamid64?: (number | null);
    withCommentsOnly?: boolean;
};

export type MapsReadMapReviewsResponse = (MapReviewsPublic);

export type MapsPutMapReviewData = {
    requestBody: MapReviewUpsert;
    xServerGroupKey?: (string | null);
};

export type MapsPutMapReviewResponse = (MapReviewPublic);

export type MapsDeleteMapReviewCommentsData = {
    mapId: number;
};

export type MapsDeleteMapReviewCommentsResponse = (MapReviewPublic);

export type MapsTriggerMapSyncResponse = (MapSyncResult);

export type ModesReadModesResponse = (Array<ModePublic>);

export type ModesReadModeByNameData = {
    modeName: string;
};

export type ModesReadModeByNameResponse = (ModePublic);

export type ModesReadModeByIdData = {
    id: number;
};

export type ModesReadModeByIdResponse = (ModePublic);

export type PlayersReadPlayersData = {
    limit?: number;
    offset?: number;
    sortBy?: 'created_at' | 'last_played_at';
    sortOrder?: 'asc' | 'desc';
};

export type PlayersReadPlayersResponse = (PlayersPublic);

export type PlayersReadPlayersBatchData = {
    requestBody: PlayersBatchRead;
};

export type PlayersReadPlayersBatchResponse = (PlayersBatchPublic);

export type PlayersSearchPlayersData = {
    limit?: number;
    offset?: number;
    q: string;
};

export type PlayersSearchPlayersResponse = (PlayersPublic);

export type PlayersCreatePlayerViewData = {
    identifier: string;
};

export type PlayersCreatePlayerViewResponse = (PlayerProfileViewsPublic);

export type PlayersReadPlayerPinnedRecordsData = {
    identifier: string;
    scope?: RecordScope;
};

export type PlayersReadPlayerPinnedRecordsResponse = (PlayerPinnedRecordsPublic);

export type PlayersCreatePlayerPinnedRecordData = {
    identifier: string;
    requestBody: PlayerPinnedRecordUpsert;
};

export type PlayersCreatePlayerPinnedRecordResponse = (PlayerPinnedRecordsPublic);

export type PlayersDeletePlayerPinnedRecordData = {
    identifier: string;
    mapId: number;
    scope?: RecordScope;
    type?: RecordType;
};

export type PlayersDeletePlayerPinnedRecordResponse = (PlayerPinnedRecordsPublic);

export type PlayersReadPlayerDailyActivityStatData = {
    identifier: string;
};

export type PlayersReadPlayerDailyActivityStatResponse = (PlayerDailyActivityStatPublic);

export type PlayersReadPlayerFollowSummaryData = {
    identifier: string;
};

export type PlayersReadPlayerFollowSummaryResponse = (PlayerFollowSummaryPublic);

export type PlayersFollowPlayerData = {
    identifier: string;
};

export type PlayersFollowPlayerResponse = (PlayerFollowSummaryPublic);

export type PlayersUnfollowPlayerData = {
    identifier: string;
};

export type PlayersUnfollowPlayerResponse = (PlayerFollowSummaryPublic);

export type PlayersReadPlayerFollowersData = {
    identifier: string;
    limit?: number;
    offset?: number;
};

export type PlayersReadPlayerFollowersResponse = (PlayersPublic);

export type PlayersReadPlayerFollowingData = {
    identifier: string;
    limit?: number;
    offset?: number;
};

export type PlayersReadPlayerFollowingResponse = (PlayersPublic);

export type PlayersReadPlayerData = {
    identifier: string;
};

export type PlayersReadPlayerResponse = (PlayerPublic);

export type PlayersUpdatePlayerData = {
    identifier: string;
    requestBody: PlayerUpdate;
};

export type PlayersUpdatePlayerResponse = (PlayerPublic);

export type PlayersUpsertPlayerFromSteamData = {
    identifier: string;
};

export type PlayersUpsertPlayerFromSteamResponse = (PlayerPublic);

export type RecordsReadRecordsData = {
    createdSince?: (string | null);
    excludeCheaters?: boolean;
    id?: (Array<(number)> | null);
    isValid?: (boolean | null);
    limit?: number;
    mapId?: (number | null);
    mapName?: (string | null);
    modeId?: (number | null);
    offset?: number;
    replayId?: (number | null);
    scope?: RecordScope;
    serverId?: (number | null);
    stage?: (number | null);
    steamid64?: (number | null);
    teleports?: (number | null);
    updatedSince?: (string | null);
};

export type RecordsReadRecordsResponse = (RecordsPublic);

export type RecordsReadRecentRecordsData = {
    isProOnly?: (boolean | null);
    limit?: number;
    offset?: number;
    pointsMoreOrEqualThan?: (number | null);
    scope?: RecordScope;
};

export type RecordsReadRecentRecordsResponse = (RecentRecordsPublic);

export type RecordsReadPbRecordsData = {
    country?: (string | null);
    excludeCheaters?: boolean;
    identifier?: (string | null);
    limit?: number;
    mapId?: (number | null);
    mapName?: (string | null);
    offset?: number;
    region?: (string | null);
    scope?: RecordScope;
    stage?: number;
    type?: RecordType;
};

export type RecordsReadPbRecordsResponse = (Array<RecordPublic>);

export type RecordsReadRecordRanksData = {
    country?: (string | null);
    scope?: RecordScope;
    type?: RecordType;
    uuidList: Array<(string)>;
};

export type RecordsReadRecordRanksResponse = (RecordRanksPublic);

export type RecordsReadRecordData = {
    recordUuid: string;
    scope?: RecordScope;
};

export type RecordsReadRecordResponse = (RecordPublic);

export type RecordsPatchRecordData = {
    recordUuid: string;
    requestBody: RecordPatch;
};

export type RecordsPatchRecordResponse = (RecordPublic);

export type RegionsReadRegionsResponse = (RegionsPublic);

export type ServerGroupsReadServerGroupsResponse = (ServerGroupsPublic);

export type ServerGroupsCreateServerGroupData = {
    requestBody: ServerGroupCreate;
};

export type ServerGroupsCreateServerGroupResponse = (ServerGroupApiKeyPublic);

export type ServerGroupsUpdateServerGroupData = {
    groupId: string;
    requestBody: ServerGroupUpdate;
};

export type ServerGroupsUpdateServerGroupResponse = (ServerGroupPublic);

export type ServerGroupsDeleteServerGroupData = {
    groupId: string;
};

export type ServerGroupsDeleteServerGroupResponse = (Message);

export type ServerGroupsRotateServerGroupApiKeyData = {
    groupId: string;
};

export type ServerGroupsRotateServerGroupApiKeyResponse = (ServerGroupApiKeyPublic);

export type ServersPutServerStatusData = {
    requestBody: ServerStatusPut;
    xServerGroupKey?: (string | null);
};

export type ServersPutServerStatusResponse = (ServerPublic);

export type ServersReadServersData = {
    city?: (string | null);
    country?: (string | null);
    groupId?: (string | null);
    limit?: number;
    offset?: number;
    online?: (boolean | null);
    region?: (string | null);
    sourceType?: (ServerSource | null);
};

export type ServersReadServersResponse = (ServersPublic);

export type ServersCreateServerData = {
    requestBody: ServerCreate;
};

export type ServersCreateServerResponse = (ServerPublic);

export type ServersTriggerServerDiscoveryResponse = (ServerDiscoveryRunPublic);

export type ServersReadServerHistoryData = {
    bucketSeconds?: number;
    fromAt?: (string | null);
    serverId: string;
    toAt?: (string | null);
};

export type ServersReadServerHistoryResponse = (ServerHistoryPublic);

export type ServersReadServerData = {
    serverId: string;
};

export type ServersReadServerResponse = (ServerPublic);

export type ServersUpdateServerData = {
    requestBody: ServerUpdate;
    serverId: string;
};

export type ServersUpdateServerResponse = (ServerPublic);

export type ServersDeleteServerData = {
    serverId: string;
};

export type ServersDeleteServerResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
    sortBy?: 'created_at' | 'last_visited_at';
    sortOrder?: 'asc' | 'desc';
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);