"""add server status tables

Revision ID: c4e58b7407f0
Revises: 6f1dfd8e63b9
Create Date: 2026-03-12 16:12:54.868552

"""
from datetime import UTC, date, datetime, timedelta

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4e58b7407f0'
down_revision = '6f1dfd8e63b9'
branch_labels = None
depends_on = None


def _server_heartbeat_partition_name(partition_date: date) -> str:
    return f"server_heartbeat_raw_p_{partition_date:%Y%m%d}"


def _create_server_heartbeat_partitions(*, start_date: date, end_date: date) -> None:
    current_date = start_date
    while current_date <= end_date:
        next_date = current_date + timedelta(days=1)
        partition_name = _server_heartbeat_partition_name(current_date)
        op.execute(
            sa.text(
                f'CREATE TABLE IF NOT EXISTS "{partition_name}" '
                "PARTITION OF server_heartbeat_raw "
                f"FOR VALUES FROM ('{current_date.isoformat()}') "
                f"TO ('{next_date.isoformat()}')"
            )
        )
        current_date = next_date


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_group',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('api_key_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('api_key_prefix', sqlmodel.sql.sqltypes.AutoString(length=12), nullable=False),
    sa.Column('api_key_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_server_group_name', 'server_group', ['name'], unique=True)
    op.create_table('server',
    sa.Column('ip', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('configured_hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Enum('manual', 'steam_master', name='server_source'), nullable=False),
    sa.Column('last_discovered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['server_group.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_server_enabled', 'server', ['enabled'], unique=False)
    op.create_index('ix_server_group_id', 'server', ['group_id'], unique=False)
    op.create_index('uq_server_ip_port', 'server', ['ip', 'port'], unique=True)
    op.create_table('server_heartbeat_raw',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('plugin', 'a2s', 'offline_mark', name='server_heartbeat_source'), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('map', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('observed_at', 'id', name='pk_server_heartbeat_raw'),
    postgresql_partition_by='RANGE (observed_at)'
    )
    op.create_index('ix_server_heartbeat_raw_server_id_observed_at', 'server_heartbeat_raw', ['server_id', 'observed_at'], unique=False)
    op.create_table('server_live_status',
    sa.Column('current_hostname', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('map', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('player_count', sa.Integer(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=False),
    sa.Column('players', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('last_plugin_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_a2s_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_successful_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('server_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['server.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('server_id')
    )
    op.create_index('ix_server_live_status_is_online', 'server_live_status', ['is_online'], unique=False)
    op.create_index('ix_server_live_status_last_a2s_seen_at', 'server_live_status', ['last_a2s_seen_at'], unique=False)
    op.create_index('ix_server_live_status_last_plugin_seen_at', 'server_live_status', ['last_plugin_seen_at'], unique=False)
    today = datetime.now(UTC).date()
    _create_server_heartbeat_partitions(
        start_date=today - timedelta(days=30),
        end_date=today + timedelta(days=7),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_live_status_last_plugin_seen_at', table_name='server_live_status')
    op.drop_index('ix_server_live_status_last_a2s_seen_at', table_name='server_live_status')
    op.drop_index('ix_server_live_status_is_online', table_name='server_live_status')
    op.drop_table('server_live_status')
    op.drop_index('ix_server_heartbeat_raw_server_id_observed_at', table_name='server_heartbeat_raw')
    op.drop_table('server_heartbeat_raw')
    op.drop_index('uq_server_ip_port', table_name='server')
    op.drop_index('ix_server_group_id', table_name='server')
    op.drop_index('ix_server_enabled', table_name='server')
    op.drop_table('server')
    op.drop_index('uq_server_group_name', table_name='server_group')
    op.drop_table('server_group')
    # ### end Alembic commands ###
