"""steam_only_auth_and_player_table

Revision ID: feb407b55a1c
Revises: fe56fa70289e
Create Date: 2026-02-27 20:16:23.008246

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'feb407b55a1c'
down_revision = 'fe56fa70289e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Start fresh auth data for Steam-only cutover.
    op.execute('TRUNCATE TABLE item, "user" CASCADE')

    op.create_table('player',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('alias', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('custom_id', sqlmodel.sql.sqltypes.AutoString(length=25), nullable=True),
    sa.Column('avatar_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('steamid64', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('steamid64')
    )
    op.add_column('user', sa.Column('steamid64', sa.BigInteger(), nullable=False))
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.create_index(op.f('ix_user_steamid64'), 'user', ['steamid64'], unique=True)
    op.create_foreign_key('user_steamid64_fkey', 'user', 'player', ['steamid64'], ['steamid64'])
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'email')
    op.drop_column('user', 'hashed_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint('user_steamid64_fkey', 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_steamid64'), table_name='user')
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_column('user', 'steamid64')
    op.drop_table('player')
    # ### end Alembic commands ###
