/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ServersServerAddressRouteImport } from './routes/servers.$serverAddress'
import { Route as MapsMapNameRouteImport } from './routes/maps.$mapName'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLiveRouteImport } from './routes/_layout/live'
import { Route as LayoutLeaderboardsRouteImport } from './routes/_layout/leaderboards'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBansRouteImport } from './routes/_layout/bans'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProfileIdentifierRouteImport } from './routes/_layout/profile.$identifier'
import { Route as LayoutDashboardRecordsRouteImport } from './routes/_layout/dashboard.records'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin.users'
import { Route as LayoutAdminPlayersRouteImport } from './routes/_layout/admin.players'
import { Route as LayoutProfileIdentifierIndexRouteImport } from './routes/_layout/profile.$identifier.index'
import { Route as LayoutProfileIdentifierStatsRouteImport } from './routes/_layout/profile.$identifier.stats'
import { Route as LayoutProfileIdentifierRecordsRouteImport } from './routes/_layout/profile.$identifier.records'

const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ServersServerAddressRoute = ServersServerAddressRouteImport.update({
  id: '/$serverAddress',
  path: '/$serverAddress',
  getParentRoute: () => ServersRoute,
} as any)
const MapsMapNameRoute = MapsMapNameRouteImport.update({
  id: '/$mapName',
  path: '/$mapName',
  getParentRoute: () => MapsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiveRoute = LayoutLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardsRoute = LayoutLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBansRoute = LayoutBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProfileIdentifierRoute = LayoutProfileIdentifierRouteImport.update({
  id: '/profile/$identifier',
  path: '/profile/$identifier',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRecordsRoute = LayoutDashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPlayersRoute = LayoutAdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutProfileIdentifierIndexRoute =
  LayoutProfileIdentifierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierStatsRoute =
  LayoutProfileIdentifierStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierRecordsRoute =
  LayoutProfileIdentifierRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/admin': typeof LayoutAdminRouteWithChildren
  '/bans': typeof LayoutBansRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/leaderboards': typeof LayoutLeaderboardsRoute
  '/live': typeof LayoutLiveRoute
  '/settings': typeof LayoutSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/admin/players': typeof LayoutAdminPlayersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/profile/$identifier': typeof LayoutProfileIdentifierRouteWithChildren
  '/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/profile/$identifier/': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/admin': typeof LayoutAdminRouteWithChildren
  '/bans': typeof LayoutBansRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/leaderboards': typeof LayoutLeaderboardsRoute
  '/live': typeof LayoutLiveRoute
  '/settings': typeof LayoutSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/': typeof LayoutIndexRoute
  '/admin/players': typeof LayoutAdminPlayersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/profile/$identifier': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/bans': typeof LayoutBansRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/leaderboards': typeof LayoutLeaderboardsRoute
  '/_layout/live': typeof LayoutLiveRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/players': typeof LayoutAdminPlayersRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/_layout/profile/$identifier': typeof LayoutProfileIdentifierRouteWithChildren
  '/_layout/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/_layout/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/_layout/profile/$identifier/': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/maps'
    | '/servers'
    | '/admin'
    | '/bans'
    | '/dashboard'
    | '/leaderboards'
    | '/live'
    | '/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/admin/players'
    | '/admin/users'
    | '/dashboard/records'
    | '/profile/$identifier'
    | '/profile/$identifier/records'
    | '/profile/$identifier/stats'
    | '/profile/$identifier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/maps'
    | '/servers'
    | '/admin'
    | '/bans'
    | '/dashboard'
    | '/leaderboards'
    | '/live'
    | '/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/'
    | '/admin/players'
    | '/admin/users'
    | '/dashboard/records'
    | '/profile/$identifier/records'
    | '/profile/$identifier/stats'
    | '/profile/$identifier'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/maps'
    | '/servers'
    | '/_layout/admin'
    | '/_layout/bans'
    | '/_layout/dashboard'
    | '/_layout/leaderboards'
    | '/_layout/live'
    | '/_layout/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/_layout/'
    | '/_layout/admin/players'
    | '/_layout/admin/users'
    | '/_layout/dashboard/records'
    | '/_layout/profile/$identifier'
    | '/_layout/profile/$identifier/records'
    | '/_layout/profile/$identifier/stats'
    | '/_layout/profile/$identifier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRouteWithChildren
  ServersRoute: typeof ServersRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/servers/$serverAddress': {
      id: '/servers/$serverAddress'
      path: '/$serverAddress'
      fullPath: '/servers/$serverAddress'
      preLoaderRoute: typeof ServersServerAddressRouteImport
      parentRoute: typeof ServersRoute
    }
    '/maps/$mapName': {
      id: '/maps/$mapName'
      path: '/$mapName'
      fullPath: '/maps/$mapName'
      preLoaderRoute: typeof MapsMapNameRouteImport
      parentRoute: typeof MapsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/live': {
      id: '/_layout/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LayoutLiveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboards': {
      id: '/_layout/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LayoutLeaderboardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bans': {
      id: '/_layout/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof LayoutBansRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/profile/$identifier': {
      id: '/_layout/profile/$identifier'
      path: '/profile/$identifier'
      fullPath: '/profile/$identifier'
      preLoaderRoute: typeof LayoutProfileIdentifierRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/records': {
      id: '/_layout/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof LayoutDashboardRecordsRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/players': {
      id: '/_layout/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof LayoutAdminPlayersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/profile/$identifier/': {
      id: '/_layout/profile/$identifier/'
      path: '/'
      fullPath: '/profile/$identifier/'
      preLoaderRoute: typeof LayoutProfileIdentifierIndexRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/stats': {
      id: '/_layout/profile/$identifier/stats'
      path: '/stats'
      fullPath: '/profile/$identifier/stats'
      preLoaderRoute: typeof LayoutProfileIdentifierStatsRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/records': {
      id: '/_layout/profile/$identifier/records'
      path: '/records'
      fullPath: '/profile/$identifier/records'
      preLoaderRoute: typeof LayoutProfileIdentifierRecordsRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminPlayersRoute: typeof LayoutAdminPlayersRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminPlayersRoute: LayoutAdminPlayersRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutDashboardRouteChildren {
  LayoutDashboardRecordsRoute: typeof LayoutDashboardRecordsRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardRecordsRoute: LayoutDashboardRecordsRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutProfileIdentifierRouteChildren {
  LayoutProfileIdentifierRecordsRoute: typeof LayoutProfileIdentifierRecordsRoute
  LayoutProfileIdentifierStatsRoute: typeof LayoutProfileIdentifierStatsRoute
  LayoutProfileIdentifierIndexRoute: typeof LayoutProfileIdentifierIndexRoute
}

const LayoutProfileIdentifierRouteChildren: LayoutProfileIdentifierRouteChildren =
  {
    LayoutProfileIdentifierRecordsRoute: LayoutProfileIdentifierRecordsRoute,
    LayoutProfileIdentifierStatsRoute: LayoutProfileIdentifierStatsRoute,
    LayoutProfileIdentifierIndexRoute: LayoutProfileIdentifierIndexRoute,
  }

const LayoutProfileIdentifierRouteWithChildren =
  LayoutProfileIdentifierRoute._addFileChildren(
    LayoutProfileIdentifierRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutBansRoute: typeof LayoutBansRoute
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutLeaderboardsRoute: typeof LayoutLeaderboardsRoute
  LayoutLiveRoute: typeof LayoutLiveRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileIdentifierRoute: typeof LayoutProfileIdentifierRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutBansRoute: LayoutBansRoute,
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutLeaderboardsRoute: LayoutLeaderboardsRoute,
  LayoutLiveRoute: LayoutLiveRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileIdentifierRoute: LayoutProfileIdentifierRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface MapsRouteChildren {
  MapsMapNameRoute: typeof MapsMapNameRoute
}

const MapsRouteChildren: MapsRouteChildren = {
  MapsMapNameRoute: MapsMapNameRoute,
}

const MapsRouteWithChildren = MapsRoute._addFileChildren(MapsRouteChildren)

interface ServersRouteChildren {
  ServersServerAddressRoute: typeof ServersServerAddressRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerAddressRoute: ServersServerAddressRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRouteWithChildren,
  ServersRoute: ServersRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
