/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServersRouteImport } from './routes/servers'
import { Route as MapsRouteImport } from './routes/maps'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as ServersServerAddressRouteImport } from './routes/servers.$serverAddress'
import { Route as MapsMapNameRouteImport } from './routes/maps.$mapName'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLiveRouteImport } from './routes/_layout/live'
import { Route as LayoutLeaderboardsRouteImport } from './routes/_layout/leaderboards'
import { Route as LayoutDashboardRouteImport } from './routes/_layout/dashboard'
import { Route as LayoutBansRouteImport } from './routes/_layout/bans'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutSettingsWebhooksRouteImport } from './routes/_layout/settings.webhooks'
import { Route as LayoutSettingsSocialLinksRouteImport } from './routes/_layout/settings.social-links'
import { Route as LayoutSettingsProfileRouteImport } from './routes/_layout/settings.profile'
import { Route as LayoutSettingsAppearanceRouteImport } from './routes/_layout/settings.appearance'
import { Route as LayoutProfileIdentifierRouteImport } from './routes/_layout/profile.$identifier'
import { Route as LayoutLeaderboardsServersRouteImport } from './routes/_layout/leaderboards.servers'
import { Route as LayoutLeaderboardsPowRouteImport } from './routes/_layout/leaderboards.pow'
import { Route as LayoutLeaderboardsPlayersRouteImport } from './routes/_layout/leaderboards.players'
import { Route as LayoutLeaderboardsMapsRouteImport } from './routes/_layout/leaderboards.maps'
import { Route as LayoutLeaderboardsJumpstatsRouteImport } from './routes/_layout/leaderboards.jumpstats'
import { Route as LayoutDashboardReviewsRouteImport } from './routes/_layout/dashboard.reviews'
import { Route as LayoutDashboardRecordsRouteImport } from './routes/_layout/dashboard.records'
import { Route as LayoutAdminUsersRouteImport } from './routes/_layout/admin.users'
import { Route as LayoutAdminServersRouteImport } from './routes/_layout/admin.servers'
import { Route as LayoutAdminPlayersRouteImport } from './routes/_layout/admin.players'
import { Route as LayoutAdminPlayerSocialLinksRouteImport } from './routes/_layout/admin.player-social-links'
import { Route as LayoutAdminPlayerSessionsRouteImport } from './routes/_layout/admin.player-sessions'
import { Route as LayoutAdminMapsRouteImport } from './routes/_layout/admin.maps'
import { Route as LayoutProfileIdentifierIndexRouteImport } from './routes/_layout/profile.$identifier.index'
import { Route as LayoutProfileIdentifierUnfinishedRouteImport } from './routes/_layout/profile.$identifier.unfinished'
import { Route as LayoutProfileIdentifierStatsRouteImport } from './routes/_layout/profile.$identifier.stats'
import { Route as LayoutProfileIdentifierRecordsRouteImport } from './routes/_layout/profile.$identifier.records'
import { Route as LayoutProfileIdentifierFriendsRouteImport } from './routes/_layout/profile.$identifier.friends'

const ServersRoute = ServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => rootRouteImport,
} as any)
const MapsRoute = MapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const ServersServerAddressRoute = ServersServerAddressRouteImport.update({
  id: '/$serverAddress',
  path: '/$serverAddress',
  getParentRoute: () => ServersRoute,
} as any)
const MapsMapNameRoute = MapsMapNameRouteImport.update({
  id: '/$mapName',
  path: '/$mapName',
  getParentRoute: () => MapsRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLiveRoute = LayoutLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardsRoute = LayoutLeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardRoute = LayoutDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutBansRoute = LayoutBansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsWebhooksRoute = LayoutSettingsWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsSocialLinksRoute =
  LayoutSettingsSocialLinksRouteImport.update({
    id: '/social-links',
    path: '/social-links',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutSettingsProfileRoute = LayoutSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutSettingsRoute,
} as any)
const LayoutSettingsAppearanceRoute =
  LayoutSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => LayoutSettingsRoute,
  } as any)
const LayoutProfileIdentifierRoute = LayoutProfileIdentifierRouteImport.update({
  id: '/profile/$identifier',
  path: '/profile/$identifier',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeaderboardsServersRoute =
  LayoutLeaderboardsServersRouteImport.update({
    id: '/servers',
    path: '/servers',
    getParentRoute: () => LayoutLeaderboardsRoute,
  } as any)
const LayoutLeaderboardsPowRoute = LayoutLeaderboardsPowRouteImport.update({
  id: '/pow',
  path: '/pow',
  getParentRoute: () => LayoutLeaderboardsRoute,
} as any)
const LayoutLeaderboardsPlayersRoute =
  LayoutLeaderboardsPlayersRouteImport.update({
    id: '/players',
    path: '/players',
    getParentRoute: () => LayoutLeaderboardsRoute,
  } as any)
const LayoutLeaderboardsMapsRoute = LayoutLeaderboardsMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => LayoutLeaderboardsRoute,
} as any)
const LayoutLeaderboardsJumpstatsRoute =
  LayoutLeaderboardsJumpstatsRouteImport.update({
    id: '/jumpstats',
    path: '/jumpstats',
    getParentRoute: () => LayoutLeaderboardsRoute,
  } as any)
const LayoutDashboardReviewsRoute = LayoutDashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutDashboardRecordsRoute = LayoutDashboardRecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => LayoutDashboardRoute,
} as any)
const LayoutAdminUsersRoute = LayoutAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminServersRoute = LayoutAdminServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPlayersRoute = LayoutAdminPlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutAdminPlayerSocialLinksRoute =
  LayoutAdminPlayerSocialLinksRouteImport.update({
    id: '/player-social-links',
    path: '/player-social-links',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminPlayerSessionsRoute =
  LayoutAdminPlayerSessionsRouteImport.update({
    id: '/player-sessions',
    path: '/player-sessions',
    getParentRoute: () => LayoutAdminRoute,
  } as any)
const LayoutAdminMapsRoute = LayoutAdminMapsRouteImport.update({
  id: '/maps',
  path: '/maps',
  getParentRoute: () => LayoutAdminRoute,
} as any)
const LayoutProfileIdentifierIndexRoute =
  LayoutProfileIdentifierIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierUnfinishedRoute =
  LayoutProfileIdentifierUnfinishedRouteImport.update({
    id: '/unfinished',
    path: '/unfinished',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierStatsRoute =
  LayoutProfileIdentifierStatsRouteImport.update({
    id: '/stats',
    path: '/stats',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierRecordsRoute =
  LayoutProfileIdentifierRecordsRouteImport.update({
    id: '/records',
    path: '/records',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)
const LayoutProfileIdentifierFriendsRoute =
  LayoutProfileIdentifierFriendsRouteImport.update({
    id: '/friends',
    path: '/friends',
    getParentRoute: () => LayoutProfileIdentifierRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/admin': typeof LayoutAdminRouteWithChildren
  '/bans': typeof LayoutBansRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/leaderboards': typeof LayoutLeaderboardsRouteWithChildren
  '/live': typeof LayoutLiveRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/admin/maps': typeof LayoutAdminMapsRoute
  '/admin/player-sessions': typeof LayoutAdminPlayerSessionsRoute
  '/admin/player-social-links': typeof LayoutAdminPlayerSocialLinksRoute
  '/admin/players': typeof LayoutAdminPlayersRoute
  '/admin/servers': typeof LayoutAdminServersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/dashboard/reviews': typeof LayoutDashboardReviewsRoute
  '/leaderboards/jumpstats': typeof LayoutLeaderboardsJumpstatsRoute
  '/leaderboards/maps': typeof LayoutLeaderboardsMapsRoute
  '/leaderboards/players': typeof LayoutLeaderboardsPlayersRoute
  '/leaderboards/pow': typeof LayoutLeaderboardsPowRoute
  '/leaderboards/servers': typeof LayoutLeaderboardsServersRoute
  '/profile/$identifier': typeof LayoutProfileIdentifierRouteWithChildren
  '/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/social-links': typeof LayoutSettingsSocialLinksRoute
  '/settings/webhooks': typeof LayoutSettingsWebhooksRoute
  '/profile/$identifier/friends': typeof LayoutProfileIdentifierFriendsRoute
  '/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/profile/$identifier/unfinished': typeof LayoutProfileIdentifierUnfinishedRoute
  '/profile/$identifier/': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/admin': typeof LayoutAdminRouteWithChildren
  '/bans': typeof LayoutBansRoute
  '/dashboard': typeof LayoutDashboardRouteWithChildren
  '/leaderboards': typeof LayoutLeaderboardsRouteWithChildren
  '/live': typeof LayoutLiveRoute
  '/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/': typeof LayoutIndexRoute
  '/admin/maps': typeof LayoutAdminMapsRoute
  '/admin/player-sessions': typeof LayoutAdminPlayerSessionsRoute
  '/admin/player-social-links': typeof LayoutAdminPlayerSocialLinksRoute
  '/admin/players': typeof LayoutAdminPlayersRoute
  '/admin/servers': typeof LayoutAdminServersRoute
  '/admin/users': typeof LayoutAdminUsersRoute
  '/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/dashboard/reviews': typeof LayoutDashboardReviewsRoute
  '/leaderboards/jumpstats': typeof LayoutLeaderboardsJumpstatsRoute
  '/leaderboards/maps': typeof LayoutLeaderboardsMapsRoute
  '/leaderboards/players': typeof LayoutLeaderboardsPlayersRoute
  '/leaderboards/pow': typeof LayoutLeaderboardsPowRoute
  '/leaderboards/servers': typeof LayoutLeaderboardsServersRoute
  '/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/settings/profile': typeof LayoutSettingsProfileRoute
  '/settings/social-links': typeof LayoutSettingsSocialLinksRoute
  '/settings/webhooks': typeof LayoutSettingsWebhooksRoute
  '/profile/$identifier/friends': typeof LayoutProfileIdentifierFriendsRoute
  '/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/profile/$identifier/unfinished': typeof LayoutProfileIdentifierUnfinishedRoute
  '/profile/$identifier': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/maps': typeof MapsRouteWithChildren
  '/servers': typeof ServersRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRouteWithChildren
  '/_layout/bans': typeof LayoutBansRoute
  '/_layout/dashboard': typeof LayoutDashboardRouteWithChildren
  '/_layout/leaderboards': typeof LayoutLeaderboardsRouteWithChildren
  '/_layout/live': typeof LayoutLiveRoute
  '/_layout/settings': typeof LayoutSettingsRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/maps/$mapName': typeof MapsMapNameRoute
  '/servers/$serverAddress': typeof ServersServerAddressRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/admin/maps': typeof LayoutAdminMapsRoute
  '/_layout/admin/player-sessions': typeof LayoutAdminPlayerSessionsRoute
  '/_layout/admin/player-social-links': typeof LayoutAdminPlayerSocialLinksRoute
  '/_layout/admin/players': typeof LayoutAdminPlayersRoute
  '/_layout/admin/servers': typeof LayoutAdminServersRoute
  '/_layout/admin/users': typeof LayoutAdminUsersRoute
  '/_layout/dashboard/records': typeof LayoutDashboardRecordsRoute
  '/_layout/dashboard/reviews': typeof LayoutDashboardReviewsRoute
  '/_layout/leaderboards/jumpstats': typeof LayoutLeaderboardsJumpstatsRoute
  '/_layout/leaderboards/maps': typeof LayoutLeaderboardsMapsRoute
  '/_layout/leaderboards/players': typeof LayoutLeaderboardsPlayersRoute
  '/_layout/leaderboards/pow': typeof LayoutLeaderboardsPowRoute
  '/_layout/leaderboards/servers': typeof LayoutLeaderboardsServersRoute
  '/_layout/profile/$identifier': typeof LayoutProfileIdentifierRouteWithChildren
  '/_layout/settings/appearance': typeof LayoutSettingsAppearanceRoute
  '/_layout/settings/profile': typeof LayoutSettingsProfileRoute
  '/_layout/settings/social-links': typeof LayoutSettingsSocialLinksRoute
  '/_layout/settings/webhooks': typeof LayoutSettingsWebhooksRoute
  '/_layout/profile/$identifier/friends': typeof LayoutProfileIdentifierFriendsRoute
  '/_layout/profile/$identifier/records': typeof LayoutProfileIdentifierRecordsRoute
  '/_layout/profile/$identifier/stats': typeof LayoutProfileIdentifierStatsRoute
  '/_layout/profile/$identifier/unfinished': typeof LayoutProfileIdentifierUnfinishedRoute
  '/_layout/profile/$identifier/': typeof LayoutProfileIdentifierIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/maps'
    | '/servers'
    | '/admin'
    | '/bans'
    | '/dashboard'
    | '/leaderboards'
    | '/live'
    | '/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/admin/maps'
    | '/admin/player-sessions'
    | '/admin/player-social-links'
    | '/admin/players'
    | '/admin/servers'
    | '/admin/users'
    | '/dashboard/records'
    | '/dashboard/reviews'
    | '/leaderboards/jumpstats'
    | '/leaderboards/maps'
    | '/leaderboards/players'
    | '/leaderboards/pow'
    | '/leaderboards/servers'
    | '/profile/$identifier'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/social-links'
    | '/settings/webhooks'
    | '/profile/$identifier/friends'
    | '/profile/$identifier/records'
    | '/profile/$identifier/stats'
    | '/profile/$identifier/unfinished'
    | '/profile/$identifier/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/maps'
    | '/servers'
    | '/admin'
    | '/bans'
    | '/dashboard'
    | '/leaderboards'
    | '/live'
    | '/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/'
    | '/admin/maps'
    | '/admin/player-sessions'
    | '/admin/player-social-links'
    | '/admin/players'
    | '/admin/servers'
    | '/admin/users'
    | '/dashboard/records'
    | '/dashboard/reviews'
    | '/leaderboards/jumpstats'
    | '/leaderboards/maps'
    | '/leaderboards/players'
    | '/leaderboards/pow'
    | '/leaderboards/servers'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/social-links'
    | '/settings/webhooks'
    | '/profile/$identifier/friends'
    | '/profile/$identifier/records'
    | '/profile/$identifier/stats'
    | '/profile/$identifier/unfinished'
    | '/profile/$identifier'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/maps'
    | '/servers'
    | '/_layout/admin'
    | '/_layout/bans'
    | '/_layout/dashboard'
    | '/_layout/leaderboards'
    | '/_layout/live'
    | '/_layout/settings'
    | '/auth/callback'
    | '/maps/$mapName'
    | '/servers/$serverAddress'
    | '/_layout/'
    | '/_layout/admin/maps'
    | '/_layout/admin/player-sessions'
    | '/_layout/admin/player-social-links'
    | '/_layout/admin/players'
    | '/_layout/admin/servers'
    | '/_layout/admin/users'
    | '/_layout/dashboard/records'
    | '/_layout/dashboard/reviews'
    | '/_layout/leaderboards/jumpstats'
    | '/_layout/leaderboards/maps'
    | '/_layout/leaderboards/players'
    | '/_layout/leaderboards/pow'
    | '/_layout/leaderboards/servers'
    | '/_layout/profile/$identifier'
    | '/_layout/settings/appearance'
    | '/_layout/settings/profile'
    | '/_layout/settings/social-links'
    | '/_layout/settings/webhooks'
    | '/_layout/profile/$identifier/friends'
    | '/_layout/profile/$identifier/records'
    | '/_layout/profile/$identifier/stats'
    | '/_layout/profile/$identifier/unfinished'
    | '/_layout/profile/$identifier/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  MapsRoute: typeof MapsRouteWithChildren
  ServersRoute: typeof ServersRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/servers': {
      id: '/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof ServersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maps': {
      id: '/maps'
      path: '/maps'
      fullPath: '/maps'
      preLoaderRoute: typeof MapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/servers/$serverAddress': {
      id: '/servers/$serverAddress'
      path: '/$serverAddress'
      fullPath: '/servers/$serverAddress'
      preLoaderRoute: typeof ServersServerAddressRouteImport
      parentRoute: typeof ServersRoute
    }
    '/maps/$mapName': {
      id: '/maps/$mapName'
      path: '/$mapName'
      fullPath: '/maps/$mapName'
      preLoaderRoute: typeof MapsMapNameRouteImport
      parentRoute: typeof MapsRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/live': {
      id: '/_layout/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LayoutLiveRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboards': {
      id: '/_layout/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LayoutLeaderboardsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard': {
      id: '/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/bans': {
      id: '/_layout/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof LayoutBansRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/webhooks': {
      id: '/_layout/settings/webhooks'
      path: '/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof LayoutSettingsWebhooksRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/social-links': {
      id: '/_layout/settings/social-links'
      path: '/social-links'
      fullPath: '/settings/social-links'
      preLoaderRoute: typeof LayoutSettingsSocialLinksRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/profile': {
      id: '/_layout/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutSettingsProfileRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/settings/appearance': {
      id: '/_layout/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof LayoutSettingsAppearanceRouteImport
      parentRoute: typeof LayoutSettingsRoute
    }
    '/_layout/profile/$identifier': {
      id: '/_layout/profile/$identifier'
      path: '/profile/$identifier'
      fullPath: '/profile/$identifier'
      preLoaderRoute: typeof LayoutProfileIdentifierRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/leaderboards/servers': {
      id: '/_layout/leaderboards/servers'
      path: '/servers'
      fullPath: '/leaderboards/servers'
      preLoaderRoute: typeof LayoutLeaderboardsServersRouteImport
      parentRoute: typeof LayoutLeaderboardsRoute
    }
    '/_layout/leaderboards/pow': {
      id: '/_layout/leaderboards/pow'
      path: '/pow'
      fullPath: '/leaderboards/pow'
      preLoaderRoute: typeof LayoutLeaderboardsPowRouteImport
      parentRoute: typeof LayoutLeaderboardsRoute
    }
    '/_layout/leaderboards/players': {
      id: '/_layout/leaderboards/players'
      path: '/players'
      fullPath: '/leaderboards/players'
      preLoaderRoute: typeof LayoutLeaderboardsPlayersRouteImport
      parentRoute: typeof LayoutLeaderboardsRoute
    }
    '/_layout/leaderboards/maps': {
      id: '/_layout/leaderboards/maps'
      path: '/maps'
      fullPath: '/leaderboards/maps'
      preLoaderRoute: typeof LayoutLeaderboardsMapsRouteImport
      parentRoute: typeof LayoutLeaderboardsRoute
    }
    '/_layout/leaderboards/jumpstats': {
      id: '/_layout/leaderboards/jumpstats'
      path: '/jumpstats'
      fullPath: '/leaderboards/jumpstats'
      preLoaderRoute: typeof LayoutLeaderboardsJumpstatsRouteImport
      parentRoute: typeof LayoutLeaderboardsRoute
    }
    '/_layout/dashboard/reviews': {
      id: '/_layout/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof LayoutDashboardReviewsRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/dashboard/records': {
      id: '/_layout/dashboard/records'
      path: '/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof LayoutDashboardRecordsRouteImport
      parentRoute: typeof LayoutDashboardRoute
    }
    '/_layout/admin/users': {
      id: '/_layout/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof LayoutAdminUsersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/servers': {
      id: '/_layout/admin/servers'
      path: '/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof LayoutAdminServersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/players': {
      id: '/_layout/admin/players'
      path: '/players'
      fullPath: '/admin/players'
      preLoaderRoute: typeof LayoutAdminPlayersRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/player-social-links': {
      id: '/_layout/admin/player-social-links'
      path: '/player-social-links'
      fullPath: '/admin/player-social-links'
      preLoaderRoute: typeof LayoutAdminPlayerSocialLinksRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/player-sessions': {
      id: '/_layout/admin/player-sessions'
      path: '/player-sessions'
      fullPath: '/admin/player-sessions'
      preLoaderRoute: typeof LayoutAdminPlayerSessionsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/admin/maps': {
      id: '/_layout/admin/maps'
      path: '/maps'
      fullPath: '/admin/maps'
      preLoaderRoute: typeof LayoutAdminMapsRouteImport
      parentRoute: typeof LayoutAdminRoute
    }
    '/_layout/profile/$identifier/': {
      id: '/_layout/profile/$identifier/'
      path: '/'
      fullPath: '/profile/$identifier/'
      preLoaderRoute: typeof LayoutProfileIdentifierIndexRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/unfinished': {
      id: '/_layout/profile/$identifier/unfinished'
      path: '/unfinished'
      fullPath: '/profile/$identifier/unfinished'
      preLoaderRoute: typeof LayoutProfileIdentifierUnfinishedRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/stats': {
      id: '/_layout/profile/$identifier/stats'
      path: '/stats'
      fullPath: '/profile/$identifier/stats'
      preLoaderRoute: typeof LayoutProfileIdentifierStatsRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/records': {
      id: '/_layout/profile/$identifier/records'
      path: '/records'
      fullPath: '/profile/$identifier/records'
      preLoaderRoute: typeof LayoutProfileIdentifierRecordsRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
    '/_layout/profile/$identifier/friends': {
      id: '/_layout/profile/$identifier/friends'
      path: '/friends'
      fullPath: '/profile/$identifier/friends'
      preLoaderRoute: typeof LayoutProfileIdentifierFriendsRouteImport
      parentRoute: typeof LayoutProfileIdentifierRoute
    }
  }
}

interface LayoutAdminRouteChildren {
  LayoutAdminMapsRoute: typeof LayoutAdminMapsRoute
  LayoutAdminPlayerSessionsRoute: typeof LayoutAdminPlayerSessionsRoute
  LayoutAdminPlayerSocialLinksRoute: typeof LayoutAdminPlayerSocialLinksRoute
  LayoutAdminPlayersRoute: typeof LayoutAdminPlayersRoute
  LayoutAdminServersRoute: typeof LayoutAdminServersRoute
  LayoutAdminUsersRoute: typeof LayoutAdminUsersRoute
}

const LayoutAdminRouteChildren: LayoutAdminRouteChildren = {
  LayoutAdminMapsRoute: LayoutAdminMapsRoute,
  LayoutAdminPlayerSessionsRoute: LayoutAdminPlayerSessionsRoute,
  LayoutAdminPlayerSocialLinksRoute: LayoutAdminPlayerSocialLinksRoute,
  LayoutAdminPlayersRoute: LayoutAdminPlayersRoute,
  LayoutAdminServersRoute: LayoutAdminServersRoute,
  LayoutAdminUsersRoute: LayoutAdminUsersRoute,
}

const LayoutAdminRouteWithChildren = LayoutAdminRoute._addFileChildren(
  LayoutAdminRouteChildren,
)

interface LayoutDashboardRouteChildren {
  LayoutDashboardRecordsRoute: typeof LayoutDashboardRecordsRoute
  LayoutDashboardReviewsRoute: typeof LayoutDashboardReviewsRoute
}

const LayoutDashboardRouteChildren: LayoutDashboardRouteChildren = {
  LayoutDashboardRecordsRoute: LayoutDashboardRecordsRoute,
  LayoutDashboardReviewsRoute: LayoutDashboardReviewsRoute,
}

const LayoutDashboardRouteWithChildren = LayoutDashboardRoute._addFileChildren(
  LayoutDashboardRouteChildren,
)

interface LayoutLeaderboardsRouteChildren {
  LayoutLeaderboardsJumpstatsRoute: typeof LayoutLeaderboardsJumpstatsRoute
  LayoutLeaderboardsMapsRoute: typeof LayoutLeaderboardsMapsRoute
  LayoutLeaderboardsPlayersRoute: typeof LayoutLeaderboardsPlayersRoute
  LayoutLeaderboardsPowRoute: typeof LayoutLeaderboardsPowRoute
  LayoutLeaderboardsServersRoute: typeof LayoutLeaderboardsServersRoute
}

const LayoutLeaderboardsRouteChildren: LayoutLeaderboardsRouteChildren = {
  LayoutLeaderboardsJumpstatsRoute: LayoutLeaderboardsJumpstatsRoute,
  LayoutLeaderboardsMapsRoute: LayoutLeaderboardsMapsRoute,
  LayoutLeaderboardsPlayersRoute: LayoutLeaderboardsPlayersRoute,
  LayoutLeaderboardsPowRoute: LayoutLeaderboardsPowRoute,
  LayoutLeaderboardsServersRoute: LayoutLeaderboardsServersRoute,
}

const LayoutLeaderboardsRouteWithChildren =
  LayoutLeaderboardsRoute._addFileChildren(LayoutLeaderboardsRouteChildren)

interface LayoutSettingsRouteChildren {
  LayoutSettingsAppearanceRoute: typeof LayoutSettingsAppearanceRoute
  LayoutSettingsProfileRoute: typeof LayoutSettingsProfileRoute
  LayoutSettingsSocialLinksRoute: typeof LayoutSettingsSocialLinksRoute
  LayoutSettingsWebhooksRoute: typeof LayoutSettingsWebhooksRoute
}

const LayoutSettingsRouteChildren: LayoutSettingsRouteChildren = {
  LayoutSettingsAppearanceRoute: LayoutSettingsAppearanceRoute,
  LayoutSettingsProfileRoute: LayoutSettingsProfileRoute,
  LayoutSettingsSocialLinksRoute: LayoutSettingsSocialLinksRoute,
  LayoutSettingsWebhooksRoute: LayoutSettingsWebhooksRoute,
}

const LayoutSettingsRouteWithChildren = LayoutSettingsRoute._addFileChildren(
  LayoutSettingsRouteChildren,
)

interface LayoutProfileIdentifierRouteChildren {
  LayoutProfileIdentifierFriendsRoute: typeof LayoutProfileIdentifierFriendsRoute
  LayoutProfileIdentifierRecordsRoute: typeof LayoutProfileIdentifierRecordsRoute
  LayoutProfileIdentifierStatsRoute: typeof LayoutProfileIdentifierStatsRoute
  LayoutProfileIdentifierUnfinishedRoute: typeof LayoutProfileIdentifierUnfinishedRoute
  LayoutProfileIdentifierIndexRoute: typeof LayoutProfileIdentifierIndexRoute
}

const LayoutProfileIdentifierRouteChildren: LayoutProfileIdentifierRouteChildren =
  {
    LayoutProfileIdentifierFriendsRoute: LayoutProfileIdentifierFriendsRoute,
    LayoutProfileIdentifierRecordsRoute: LayoutProfileIdentifierRecordsRoute,
    LayoutProfileIdentifierStatsRoute: LayoutProfileIdentifierStatsRoute,
    LayoutProfileIdentifierUnfinishedRoute:
      LayoutProfileIdentifierUnfinishedRoute,
    LayoutProfileIdentifierIndexRoute: LayoutProfileIdentifierIndexRoute,
  }

const LayoutProfileIdentifierRouteWithChildren =
  LayoutProfileIdentifierRoute._addFileChildren(
    LayoutProfileIdentifierRouteChildren,
  )

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRouteWithChildren
  LayoutBansRoute: typeof LayoutBansRoute
  LayoutDashboardRoute: typeof LayoutDashboardRouteWithChildren
  LayoutLeaderboardsRoute: typeof LayoutLeaderboardsRouteWithChildren
  LayoutLiveRoute: typeof LayoutLiveRoute
  LayoutSettingsRoute: typeof LayoutSettingsRouteWithChildren
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProfileIdentifierRoute: typeof LayoutProfileIdentifierRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRouteWithChildren,
  LayoutBansRoute: LayoutBansRoute,
  LayoutDashboardRoute: LayoutDashboardRouteWithChildren,
  LayoutLeaderboardsRoute: LayoutLeaderboardsRouteWithChildren,
  LayoutLiveRoute: LayoutLiveRoute,
  LayoutSettingsRoute: LayoutSettingsRouteWithChildren,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProfileIdentifierRoute: LayoutProfileIdentifierRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface MapsRouteChildren {
  MapsMapNameRoute: typeof MapsMapNameRoute
}

const MapsRouteChildren: MapsRouteChildren = {
  MapsMapNameRoute: MapsMapNameRoute,
}

const MapsRouteWithChildren = MapsRoute._addFileChildren(MapsRouteChildren)

interface ServersRouteChildren {
  ServersServerAddressRoute: typeof ServersServerAddressRoute
}

const ServersRouteChildren: ServersRouteChildren = {
  ServersServerAddressRoute: ServersServerAddressRoute,
}

const ServersRouteWithChildren =
  ServersRoute._addFileChildren(ServersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  MapsRoute: MapsRouteWithChildren,
  ServersRoute: ServersRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
