name: Deploy to Production

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  deploy:
    # Do not deploy in the main repository, only in user projects
    if: github.repository_owner != 'fastapi'
    runs-on:
      - self-hosted
      - production
    env:
      ENVIRONMENT: production
      DOMAIN: ${{ secrets.DOMAIN_PRODUCTION }}
      STACK_NAME: ${{ secrets.STACK_NAME_PRODUCTION }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      SUPER_USER_STEAMID64: ${{ secrets.SUPER_USER_STEAMID64 }}
      STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      GEOIPUPDATE_ACCOUNT_ID: ${{ secrets.GEOIPUPDATE_ACCOUNT_ID }}
      GEOIPUPDATE_LICENSE_KEY: ${{ secrets.GEOIPUPDATE_LICENSE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          clean: false
          fetch-depth: 0
      - name: Write deployment env file
        run: |
          mkdir -p "${RUNNER_WORKSPACE}/../_geoip/${STACK_NAME}"
          VITE_APP_VERSION="$(bash scripts/get-app-version.sh)"
          cat > .env <<EOF
          DOMAIN=${DOMAIN}
          API_HOST=api.${DOMAIN}
          FRONTEND_HOSTNAME=${DOMAIN}
          FRONTEND_HOST=https://${DOMAIN}
          ADMINER_HOST=adminer.${DOMAIN}
          ENVIRONMENT=${ENVIRONMENT}
          PROJECT_NAME=GOKZ.TOP
          STACK_NAME=${STACK_NAME}
          BACKEND_CORS_ORIGINS=https://${DOMAIN},https://api.${DOMAIN}
          SECRET_KEY=${SECRET_KEY}
          SUPER_USER_STEAMID64=${SUPER_USER_STEAMID64}
          STEAM_API_KEY=${STEAM_API_KEY}
          POSTGRES_PORT=5432
          POSTGRES_DB=app
          POSTGRES_USER=postgres
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          SENTRY_DSN=${SENTRY_DSN}
          GEOIP_DATA_DIR=${RUNNER_WORKSPACE}/../_geoip/${STACK_NAME}
          GEOIPUPDATE_ACCOUNT_ID=${GEOIPUPDATE_ACCOUNT_ID}
          GEOIPUPDATE_LICENSE_KEY=${GEOIPUPDATE_LICENSE_KEY}
          DOCKER_IMAGE_BACKEND=${STACK_NAME}-backend
          DOCKER_IMAGE_FRONTEND=${STACK_NAME}-frontend
          VITE_APP_VERSION=${VITE_APP_VERSION}
          EOF
      - run: docker compose -f compose.yml --project-name "${STACK_NAME}" build
      - run: docker compose -f compose.yml --project-name "${STACK_NAME}" up -d
