name: Test Docker Compose

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:

  test-docker-compose:
    runs-on: ubuntu-latest
    env:
      FRONTEND_HOST_RULE: 'Host(`localhost`)'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Seed CI env
        run: cp .env.example .env
      - run: docker compose -f compose.yml -f compose.override.yml build
      - run: docker compose -f compose.yml -f compose.override.yml down -v --remove-orphans
      - run: docker compose -f compose.yml -f compose.override.yml up -d --wait backend frontend adminer
      - name: Test backend is up
        run: curl http://localhost:8000/v1/utils/health-check/
      - name: Test frontend is up
        run: curl http://localhost:5173
      - run: docker compose -f compose.yml -f compose.override.yml down -v --remove-orphans
